(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var k=this||self,q=function(a){return a};var aa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};const ba=Array.prototype.every?function(a,b){return Array.prototype.every.call(a,b,void 0)}:function(a,b){const d=a.length,c="string"===typeof a?a.split(""):a;for(let e=0;e<d;e++)if(e in c&&!b.call(void 0,c[e],e,a))return!1;return!0};var ca={},r=null,da=function(a){var b;void 0===b&&(b=0);if(!r){r={};for(var d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),c=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=d.concat(c[e].split(""));ca[e]=f;for(var g=0;g<f.length;g++){var h=f[g];void 0===r[h]&&(r[h]=g)}}}b=ca[b];d=Array(Math.floor(a.length/3));c=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var m=a[f],l=a[f+1];h=a[f+2];g=b[m>>2];m=b[(m&3)<<4|l>>4];l=b[(l&15)<<2|h>>6];h=b[h&63];d[e++]=""+g+m+l+h}g=0;h=c;switch(a.length-
f){case 2:g=a[f+1],h=b[(g&15)<<2]||c;case 1:a=a[f],d[e]=""+b[a>>2]+b[(a&3)<<4|g>>4]+h+c}return d.join("")};var t="undefined"!==typeof Uint8Array,ea={};let fa;var u=class{constructor(a){if(ea!==ea)throw Error("illegal external caller");this.v=a;if(null!=a&&0===a.length)throw Error("ByteString should be constructed with non-empty values");}};const v="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function w(a,b){Object.isFrozen(a)||(v?a[v]|=b:void 0!==a.m?a.m|=b:Object.defineProperties(a,{m:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}function x(a){let b;v?b=a[v]:b=a.m;return null==b?0:b}function y(a){w(a,1);return a}function z(a){return Array.isArray(a)?!!(x(a)&2):!1}function A(a){if(!Array.isArray(a))throw Error("cannot mark non-array as immutable");w(a,2)}
function B(a,b){if(!Array.isArray(a))throw Error("cannot mark non-array as mutable");b?w(a,8):Object.isFrozen(a)||(v?a[v]&=-9:void 0!==a.m&&(a.m&=-9))};function C(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}let D;var E=Object.freeze(y([])),F=function(a){if(z(a.h))throw Error("Cannot mutate an immutable Message");},ha="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;function ia(a){return{value:a,configurable:!1,writable:!1,enumerable:!1}};function ja(a,b){if(Array.isArray(a))return new b(a)};function ka(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)){if(t&&null!=a&&a instanceof Uint8Array)return da(a);if(a instanceof u){var b=a.v;b=null==b||"string"===typeof b?b:t&&b instanceof Uint8Array?da(b):null;return null==b?"":a.v=b}}}return a};function G(a,b=la){return ma(a,b)}function na(a,b){if(null!=a){if(Array.isArray(a))a=ma(a,b);else if(C(a)){const d={};for(let c in a)d[c]=na(a[c],b);a=d}else a=b(a);return a}}function ma(a,b){const d=a.slice();for(let c=0;c<d.length;c++)d[c]=na(d[c],b);Array.isArray(a)&&x(a)&1&&y(d);return d}function oa(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a=ka(a);return Array.isArray(a)?G(a,oa):a}
function la(a){if("object"===typeof a){if(t&&null!=a&&a instanceof Uint8Array)return new Uint8Array(a);if(Array.isArray(a.h)&&a.constructor!==Object){var b;H=b=G(a.h);b=new a.constructor(b);H=null;I(b,a);return b}}return a};var pa=function(a){return a.i||(a.i=a.h[a.j+a.l]={})},J=function(a,b,d=!1){return-1===b?null:b>=a.j?a.i?a.i[b]:void 0:d&&a.i&&(d=a.i[b],null!=d)?d:a.h[b+a.l]},L=function(a,b,d,c=!1,e=!1){e||F(a);if(b>=a.j||c)return pa(a)[b]=d,a;void 0!==a.i&&a.j>=a.h.length?(c=a.h.length-1,e=b+a.l,e>=c?(a.h[c]=void 0,a.h[e]=d,a.h.push(a.i)):a.h[e]=d):a.h[b+a.l]=d;void 0!==a.i&&b in a.i&&delete a.i[b];return a},O=function(a,b){return Array.isArray(J(a,M(a,N,b)))},qa=function(a,b,d=!0,c){let e=J(a,b,c);Array.isArray(e)||
(e=E);if(z(a.h))d&&(A(e),Object.freeze(e));else if(e===E||z(e))e=y(e.slice()),L(a,b,e,c);return e},P=function(a,b){a=J(a,b);a=null==a?a:!!a;return null==a?!1:a};function ra(a,b,d,c){F(a);d!==c?L(a,b,d):L(a,b,void 0,!1);return a}function M(a,b,d){return Q(a,b)===d?d:-1}
var Q=function(a,b){let d=0;for(let c=0;c<b.length;c++){const e=b[c];null!=J(a,e)&&(0!==d&&L(a,d,void 0,!1,!0),d=e)}return d},R=function(a,b,d,c=!1){{a.g||(a.g={});const e=a.g[d];if(e)b=e;else if(b=ja(J(a,d,c),b))a.g[d]=b,z(a.h)&&A(b.h)}if(null==b)return b;z(b.h)&&!z(a.h)&&(b=b.u(),L(a,d,b.h,c),a.g[d]=b);return b},sa=function(a,b,d,c,e=!0){a.g||(a.g={});var f=z(a.h);let g=a.g[d];c=qa(a,d,!0,c);const h=f||z(c);if(!g){g=[];f=f||h;for(let l=0;l<c.length;l++){var m=c[l];f=f||z(m);m=ja(m,b);void 0!==m&&
(g.push(m),h&&A(m.h))}a.g[d]=g;B(c,!f)}b=h||e;e=z(g);b&&!e&&(Object.isFrozen(g)&&(a.g[d]=g=g.slice()),A(g),Object.freeze(g));!b&&e&&(a.g[d]=g=g.slice());return g},ta=function(a,b,d,c=!1){const e=z(a.h);b=sa(a,b,d,c,e);a=qa(a,d,c);if(!(d=e)&&(d=a)){if(!Array.isArray(a))throw Error("cannot check mutability state of non-array");d=!(x(a)&8)}if(d){for(d=0;d<b.length;d++)(c=b[d])&&z(c.h)&&!e&&(b[d]=b[d].u(),a[d]=b[d].h);B(a,!0)}return b},S=function(a,b){a=J(a,b);return null==a?0:a},T=function(a,b){a=J(a,
b);return null==a?"":a};var ua=class{constructor(a,b,d){a||(a=H);H=null;var c=this.constructor.g||0,e=0<c;let f=this.constructor.i;a||(a=f?[f]:[]);e&&0<a.length&&C(a[a.length-1])&&"g"in a[a.length-1]&&(c=0);this.l=(f?0:-1)-c;this.g=void 0;this.h=a;a:{c=this.h.length;a=c-1;if(c&&(c=this.h[a],C(c))){this.i=c;b=Object.keys(c);0<b.length&&ba(b,isNaN)?this.j=Number.MAX_VALUE:this.j=a-this.l;break a}void 0!==b&&-1<b?(this.j=Math.max(b,a+1-this.l),this.i=void 0):this.j=Number.MAX_VALUE}if(!e&&this.i&&"g"in this.i)throw Error('Unexpected "g" flag in sparse object of message that is not a group type.');
if(d)for(e=0;e<d.length;e++)b=d[e],b<this.j?(b+=this.l,(a=this.h[b])?Array.isArray(a)&&y(a):this.h[b]=E):(a=pa(this),(c=a[b])?Array.isArray(c)&&y(c):a[b]=E)}toJSON(){const a=this.h;return D?a:G(a,oa)}};ua.prototype.toString=function(){return this.h.toString()};function va(a,b){return ka(b)}
function I(a,b){b.s&&(a.s=b.s.slice());const d=b.g;if(d){b=b.i;for(let f in d){const g=d[f];if(g){var c=!(!b||!b[f]),e=+f;if(Array.isArray(g)){if(g.length)for(c=ta(a,g[0].constructor,e,c),e=0;e<Math.min(c.length,g.length);e++)I(c[e],g[e])}else(c=R(a,g.constructor,e,c))&&I(c,g)}}}}let H;var wa=class extends ua{u(){return this}};ha&&Object.defineProperties(wa,{[Symbol.hasInstance]:ia(()=>{throw Error("Cannot perform instanceof checks for MutableMessage");})});function xa(a,b,d,c,e,f){if(a=a.g&&a.g[d])if(Array.isArray(a)){e=f.o?y(a.slice()):a;F(b);if(null!=e){f=y([]);c=!1;for(a=0;a<e.length;a++)f[a]=e[a].h,c=c||z(f[a]);b.g||(b.g={});b.g[d]=e;B(f,!c)}else b.g&&(b.g[d]=void 0),f=E;L(b,d,f)}else e=a,F(b),b.g||(b.g={}),null==e?f=e=void 0:f=e.h,b.g[d]=e,L(b,d,f);else t&&c instanceof Uint8Array?e=c.length?new u(new Uint8Array(c)):fa||(fa=new u(null)):(Array.isArray(c)&&(e?A(c):Array.isArray(c)&&x(c)&1&&f.o&&(c=c.slice())),e=c),L(b,d,e)};class U extends wa{u(){if(z(this.h)){var {o:a}={o:!0};a={o:a};const d=z(this.h);if(d&&!a.o)throw Error("copyRepeatedFields must be true for frozen messages");const c=new this.constructor;this.s&&(c.s=this.s.slice());const e=this.h;for(let f=0;f<e.length;f++){const g=e[f];if(f===e.length-1&&C(g))for(b in g){const h=+b;Number.isNaN(h)?pa(c)[b]=g[b]:xa(this,c,h,g[b],d,a)}else xa(this,c,f-this.l,g,d,a)}var b=c}else b=this;return b}}ha&&Object.defineProperties(U,{[Symbol.hasInstance]:ia(Object[Symbol.hasInstance])});var ya=class extends U{constructor(a){super(a)}},V=[2,3,4];var za=class extends U{constructor(a){super(a)}};var Aa=class extends U{constructor(a){super(a)}};var Ca=class extends U{constructor(a){super(a,-1,Ba)}},Ba=[6];var Da=class extends U{constructor(){super(void 0)}};var Ea=class extends U{constructor(){super(void 0)}},Fa=[2];var Ha=class extends U{constructor(a){super(a,-1,Ga)}},Ga=[2];var Ia=class extends U{constructor(a){super(a)}};var Ja=class extends U{constructor(a){super(a)}};var Ka=class extends U{constructor(a){super(a)}};var La=class extends U{constructor(a){super(a)}},N=[2,3,4,5,6,7];/*

 SPDX-License-Identifier: Apache-2.0
*/
var W;var Oa=function(a,b){this.i=a===Ma&&b||"";this.g=Na},Na={},Ma={};var Qa=class{constructor(a,b){this.g=b===Pa?a:""}toString(){return this.g+""}},Pa={};var Ra=function(){this.g=document||{cookie:""}};
Ra.prototype.set=function(a,b,d){let c,e,f,g=!1,h;"object"===typeof d&&(h=d.C,g=d.D||!1,f=d.domain||void 0,e=d.path||void 0,c=d.B);if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');void 0===c&&(c=-1);this.g.cookie=a+"="+b+(f?";domain="+f:"")+(e?";path="+e:"")+(0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*c)).toUTCString())+(g?";secure":"")+(null!=h?";samesite="+h:"")};
Ra.prototype.get=function(a,b){const d=a+"=",c=(this.g.cookie||"").split(";");for(let e=0,f;e<c.length;e++){f=aa(c[e]);if(0==f.lastIndexOf(d,0))return f.slice(d.length);if(f==a)return""}return b};class Sa{constructor(){this.i=new Ra;this.g="";this.j=a=>{a:{let n;try{var b=a.data;if(null==b||""==b)n=new La;else{var d=JSON.parse(b);if(!Array.isArray(d)){var c=typeof d;throw Error("Expected to deserialize an Array but got "+("object"!=c?c:d?Array.isArray(d)?"array":c:"null")+": "+d);}H=d;var e=new La(d);H=null;n=e}}catch(K){break a}if(O(n,4)){c=R(n,Ca,M(n,N,4));var f=ta(c,ya,6),g;f.length&&(g=Ta(f));f={event:T(c,1)||void 0,category:T(c,2)||void 0,action:T(c,3)||void 0,label:T(c,4)||void 0,value:S(c,
5)||void 0,nonInteraction:P(c,13)?"True":"False",additionalParams:g||void 0};if(Array.isArray(J(c,12))){var h=R(c,Aa,12);f.recommendations={targetPage:T(h,1),targetType:S(h,2),targetRank:S(h,3),targetIdenticalDescriptions:S(h,4),targetTitleWords:S(h,5),targetDescriptionWords:S(h,6),experiment:T(h,7)};g="";for(var m of window.dataLayer)if("experiment"in m&&"baseIds"in m.experiment){g=m.experiment.baseIds;break}(g=Ua(g,T(h,7)))&&P(h,8)&&(f.experiment={ids:g})}else f.recommendations={targetPage:void 0,
targetType:void 0,targetRank:void 0,targetIdenticalDescriptions:void 0,targetTitleWords:void 0,targetDescriptionWords:void 0};if(!("experiment"in f))for(var l of window.dataLayer)if("experiment"in l&&"ids"in l.experiment&&l.experiment.ids){f.experiment={ids:l.experiment.ids};break}m=R(c,za,11);if(Array.isArray(J(c,11))&&null!==m){c=Va(m);for(var p of Object.keys(c))f[p]=c[p]}window.dataLayer.push(f)}else if(O(n,3)){c=R(n,Ha,M(n,N,3));f=ta(c,ya,2);let K;f.length&&(K=Ta(f));f={event:"trackPageview",
pageName:T(c,1),additionalParams:K||void 0,nonInteraction:P(c,3)||void 0,ratingsCount:S(c,4)||void 0,ratingsValue:S(c,5)||void 0};p=R(c,za,6);if(Array.isArray(J(c,6))&&null!==p){c=Va(p);for(h of Object.keys(c))f[h]=c[h]}window.dataLayer.push(f)}else if(O(n,7))c=R(n,Ia,M(n,N,7)),window.dataLayer.push({parentContext:{referrer:T(c,2)||"",_ga_devsiteCookie:T(c,1)||""}});else if(O(n,6))c=R(n,Ja,M(n,N,6)),f=this.g,p=R(c,Aa,9)||new Aa,m=T(c,10)||void 0,c={experiment:{ids:(P(p,8)?Ua(m,T(p,7)):m)||void 0,
baseIds:m||void 0},hostContext:{internalUser:T(c,1)||void 0,pageType:T(c,8)||void 0,projectName:T(c,6)||void 0,signedIn:T(c,2)||void 0,tenant:T(c,5)||void 0,thirdPartyCookieAccepted:f.length?"True":"False"},language:{machineTranslated:T(c,7)||void 0,requested:T(c,3)||void 0,served:T(c,4)||void 0},recommendations:{sourcePage:T(p,1),sourceType:S(p,2),sourceRank:S(p,3),sourceIdenticalDescriptions:S(p,4),sourceTitleWords:S(p,5),sourceDescriptionWords:S(p,6),experiment:T(p,7)}},window.dataLayer.push(c);
else if(O(n,5))c=R(n,Ka,M(n,N,5)),window.dataLayer.push({originalUrlParameters:{dclid:T(c,1)||void 0,gclid:T(c,2)||void 0,utmCampaign:T(c,3)||void 0,utmContent:T(c,4)||void 0,utmMedium:T(c,5)||void 0,utmSource:T(c,6)||void 0,utmTerm:T(c,7)||void 0}});else if(2===Q(n,N)){window.dataLayer=window.dataLayer||[];window.dataLayer.push({"gtm.start":(new Date).getTime(),event:"gtm.js"});p=document.getElementsByTagName("script")[0];m=document.createElement("script");m.async=!0;l=new Oa(Ma,"//www.googletagmanager.com/gtm.js?id=GTM-PBZPJDG");
l=l instanceof Oa&&l.constructor===Oa&&l.g===Na?l.i:"type_error:Const";if(void 0===W)if(h=null,(g=k.trustedTypes)&&g.createPolicy){try{h=g.createPolicy("goog#html",{createHTML:q,createScript:q,createScriptURL:q})}catch(K){k.console&&k.console.error(K.message)}W=h}else W=h;l=(h=W)?h.createScriptURL(l):l;h=new Qa(l,Pa);l=m;l.src=h instanceof Qa&&h.constructor===Qa?h.g:"type_error:TrustedResourceUrl";(c=(h=null==(f=(c=(l.ownerDocument&&l.ownerDocument.defaultView||window).document).querySelector)?void 0:
f.call(c,"script[nonce]"))?h.nonce||h.getAttribute("nonce")||"":"")&&l.setAttribute("nonce",c);p.parentNode.insertBefore(m,p)}}};window.addEventListener("message",this.j)}A(a){this.g=this.i.get("_ga_devsite")||"";var b=new Da;a=ra(b,1,a,!1);b=ra(a,2,this.g,"");a=new Ea;F(a);a.g||(a.g={});var d=null!=b?b.h:b=void 0;a.g[2]=b;b=d;F(a);(d=Q(a,Fa))&&2!==d&&null!=b&&(a.g&&d in a.g&&(a.g[d]=void 0),L(a,d));a=L(a,2,b);if(window.parent!==window){b=window.parent;d=b.postMessage;a:{D=!0;try{var c=JSON.stringify(a.toJSON(),
va);break a}finally{D=!1}c=void 0}d.call(b,c,"*")}}}Sa.prototype.notifyIframeReady=Sa.prototype.A;function Ta(a){const b={};for(const d of a){a=T(d,1);let c;T(d,M(d,V,2))?c=T(d,M(d,V,2)):S(d,M(d,V,3))?c=S(d,M(d,V,3)):4===Q(d,V)&&(c=P(d,M(d,V,4))?"True":"False");b[a]=c}return b}
function Va(a){const b={};if(!a)return b;b.hasProfile=P(a,6)?"True":"False";b.practitionerType=T(a,1)||"Property not set";b.profileCreationMethod=T(a,4)||"Property not set";b.profileHasInterests=P(a,12)?"True":"False";b.profileInterests=T(a,13)||"Property not set";b.profileHasJobTitle=P(a,10)?"True":"False";b.profileHasLocation=P(a,7)?"True":"False";b.profileHasPronoun=P(a,9)?"True":"False";b.profileIsPublic=P(a,8)?"True":"False";b.profileSocialLinks=T(a,11)||"Property not set";b.profileBadgeEmailOptIn=
P(a,5)?"True":"False";b.profileFeedbackEmailOptIn=P(a,2)?"True":"False";b.profileNewsletterEmailOptIn=P(a,3)?"True":"False";return b}function Ua(a,b){if(a||b){if(a&&!b)return a;if(b&&!a)return b;b=new Set(b.split(","));a=[...(new Set([...(new Set(a.split(","))),...b]))];a.sort();return a.join(",")}}var Wa=Sa,X=["AnalyticsLibrary"],Y=k;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||void 0===Wa?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Wa;}).call(this);
