(function(_ds){var window=this;var eP=function(){let a;a='<div class="devsite-code-buttons-container" role="group" aria-label="'+_ds.cw("Action buttons");return(0,_ds.P)(a+'"></div>')},fP=function(a){a=a.label;return(0,_ds.P)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.T(a)+'" data-title="'+_ds.T(a)+'"></button>')},gP=function(a){a=
a.label;return(0,_ds.P)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+_ds.T(a)+'" data-title="'+_ds.T(a)+'"></button>')},hP=function(a){var b=a.label;return(0,_ds.P)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="'+
_ds.T(a.Go)+'" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.T(b)+'" data-title="'+_ds.T(b)+'"></button>')},iP=function(a){a=a.label;return(0,_ds.P)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+_ds.T(a)+'" data-title="'+_ds.T(a)+'"></button>')};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(Q){return Q.replace(t,"&amp;").replace(v,"&lt;").replace(w,"&gt;")}function b(Q,Y,la){switch(Q.nodeType){case 1:var na=Q.tagName.toLowerCase();Y.push("<",na);var ta=Q.attributes,Fa=ta.length;if(Fa){if(la){for(var Aa=[],qa=Fa;0<=--qa;)Aa[qa]=ta[qa];Aa.sort(function(ra,Pa){return ra.name<Pa.name?-1:ra.name===Pa.name?0:1});ta=Aa}for(qa=0;qa<Fa;++qa)Aa=ta[qa],Aa.specified&&Y.push(" ",Aa.name.toLowerCase(),'="',Aa.value.replace(t,"&amp;").replace(v,"&lt;").replace(w,"&gt;").replace(z,
"&quot;"),'"')}Y.push(">");for(ta=Q.firstChild;ta;ta=ta.nextSibling)b(ta,Y,la);!Q.firstChild&&/^(?:br|link|img)$/.test(na)||Y.push("</",na,">");break;case 3:case 4:Y.push(a(Q.nodeValue))}}function c(Q){function Y(ca){if("\\"!==ca.charAt(0))return ca.charCodeAt(0);switch(ca.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(ca.substring(2),16)||ca.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(ca.substring(1),
8);default:return ca.charCodeAt(1)}}function la(ca){if(32>ca)return(16>ca?"\\x0":"\\x")+ca.toString(16);ca=String.fromCharCode(ca);if("\\"===ca||"-"===ca||"["===ca||"]"===ca)ca="\\"+ca;return ca}function na(ca){var fa=ca.substring(1,ca.length-1).match(RegExp("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"));ca=[];for(var Z=[],za="^"===fa[0],ha=za?1:0,ua=fa.length;ha<ua;++ha){var ma=fa[ha];switch(ma){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":ca.push(ma);
continue}ma=Y(ma);if(ha+2<ua&&"-"===fa[ha+1]){var Ua=Y(fa[ha+2]);ha+=2}else Ua=ma;Z.push([ma,Ua]);65>Ua||122<ma||(65>Ua||90<ma||Z.push([Math.max(65,ma)|32,Math.min(Ua,90)|32]),97>Ua||122<ma||Z.push([Math.max(97,ma)&-33,Math.min(Ua,122)&-33]))}Z.sort(function(Vb,$d){return Vb[0]-$d[0]||$d[1]-Vb[1]});fa=[];ma=[NaN,NaN];for(ha=0;ha<Z.length;++ha)ua=Z[ha],ua[0]<=ma[1]+1?ma[1]=Math.max(ma[1],ua[1]):fa.push(ma=ua);Z=["["];za&&Z.push("^");Z.push.apply(Z,ca);for(ha=0;ha<fa.length;++ha)ua=fa[ha],Z.push(la(ua[0])),
ua[1]>ua[0]&&(ua[1]+1>ua[0]&&Z.push("-"),Z.push(la(ua[1])));Z.push("]");return Z.join("")}function ta(ca){for(var fa=ca.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),Z=fa.length,za=[],ha=0,ua=0;ha<Z;++ha){var ma=fa[ha];"("===ma?++ua:"\\"===ma.charAt(0)&&(ma=+ma.substring(1))&&ma<=ua&&(za[ma]=-1)}for(ha=1;ha<za.length;++ha)-1===za[ha]&&(za[ha]=++Fa);for(ua=ha=0;ha<
Z;++ha)ma=fa[ha],"("===ma?(++ua,void 0===za[ua]&&(fa[ha]="(?:")):"\\"===ma.charAt(0)&&(ma=+ma.substring(1))&&ma<=ua&&(fa[ha]="\\"+za[ua]);for(ua=ha=0;ha<Z;++ha)"^"===fa[ha]&&"^"!==fa[ha+1]&&(fa[ha]="");if(ca.ignoreCase&&Aa)for(ha=0;ha<Z;++ha)ma=fa[ha],ca=ma.charAt(0),2<=ma.length&&"["===ca?fa[ha]=na(ma):"\\"!==ca&&(fa[ha]=ma.replace(/[a-zA-Z]/g,function(Ua){Ua=Ua.charCodeAt(0);return"["+String.fromCharCode(Ua&-33,Ua|32)+"]"}));return fa.join("")}for(var Fa=0,Aa=!1,qa=!1,ra=0,Pa=Q.length;ra<Pa;++ra){var Qa=
Q[ra];if(Qa.ignoreCase)qa=!0;else if(/[a-z]/i.test(Qa.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){Aa=!0;qa=!1;break}}var Ea=[];ra=0;for(Pa=Q.length;ra<Pa;++ra){Qa=Q[ra];if(Qa.global||Qa.multiline)throw Error(""+Qa);Ea.push("(?:"+ta(Qa)+")")}return new RegExp(Ea.join("|"),qa?"gi":"g")}function d(Q){var Y=0;return function(la){for(var na=null,ta=0,Fa=0,Aa=la.length;Fa<Aa;++Fa)switch(la.charAt(Fa)){case "\t":na||(na=[]);na.push(la.substring(ta,Fa));ta=Q-Y%Q;for(Y+=ta;0<=ta;ta-=16)na.push("                ".substring(0,
ta));ta=Fa+1;break;case "\n":Y=0;break;default:++Y}if(!na)return la;na.push(la.substring(ta));return na.join("")}}function e(Q,Y,la,na){Y&&(Q={source:Y,fk:Q},la(Q),na.push.apply(na,Q.xk))}function f(Q,Y){var la={},na;(function(){for(var Aa=Q.concat(Y),qa=[],ra={},Pa=0,Qa=Aa.length;Pa<Qa;++Pa){var Ea=Aa[Pa],ca=Ea[3];if(ca)for(var fa=ca.length;0<=--fa;)la[ca.charAt(fa)]=Ea;Ea=Ea[1];ca=""+Ea;ra.hasOwnProperty(ca)||(qa.push(Ea),ra[ca]=null)}qa.push(/[\0-\uffff]/);na=c(qa)})();var ta=Y.length,Fa=function(Aa){for(var qa=
Aa.fk,ra=[qa,"pln"],Pa=0,Qa=Aa.source.match(na)||[],Ea={},ca=0,fa=Qa.length;ca<fa;++ca){var Z=Qa[ca],za=Ea[Z],ha=void 0;if("string"===typeof za)var ua=!1;else{var ma=la[Z.charAt(0)];if(ma)ha=Z.match(ma[1]),za=ma[0];else{for(ua=0;ua<ta;++ua)if(ma=Y[ua],ha=Z.match(ma[1])){za=ma[0];break}ha||(za="pln")}!(ua=5<=za.length&&"lang-"===za.substring(0,5))||ha&&"string"===typeof ha[1]||(ua=!1,za="src");ua||(Ea[Z]=za)}ma=Pa;Pa+=Z.length;if(ua){ua=ha[1];var Ua=Z.indexOf(ua),Vb=Ua+ua.length;ha[2]&&(Vb=Z.length-
ha[2].length,Ua=Vb-ua.length);za=za.substring(5);e(qa+ma,Z.substring(0,Ua),Fa,ra);e(qa+ma+Ua,ua,l(za,ua),ra);e(qa+ma+Vb,Z.substring(Vb),Fa,ra)}else ra.push(qa+ma,za)}Aa.xk=ra};return Fa}function g(Q){var Y=[],la=[];Q.tripleQuotedStrings?Y.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,null,"'\""]):Q.multiLineStrings?Y.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,
null,"'\"`"]):Y.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);Q.verbatimStrings&&la.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var na=Q.hashComments;na&&(Q.cStyleComments?(1<na?Y.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):Y.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,null,"#"]),la.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):
Y.push(["com",/^#[^\r\n]*/,null,"#"]));Q.cStyleComments&&(la.push(["com",/^\/\/[^\r\n]*/,null]),la.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));Q.regexLiterals&&la.push(["lang-regex",new RegExp("^"+n+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);Q=Q.keywords.replace(/^\s+|\s+$/g,"");Q.length&&la.push(["kwd",new RegExp("^(?:"+Q.replace(/\s+/g,"|")+")\\b"),null]);Y.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);la.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,
null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",RegExp("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*","i"),null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return f(Y,la)}function h(Q){function Y(Qe){if(Qe>ra){Pa&&Pa!==Qa&&(qa.push("</span>"),Pa=null);!Pa&&Qa&&(Pa=Qa,qa.push('<span class="',Pa,'">'));var Ol=a(fa(la.substring(ra,Qe))).replace(ma?za:Z,"$1&#160;");ma=ua.test(Ol);qa.push(Ol.replace(ha,Nl));ra=
Qe}}var la=Q.source,na=Q.Vo,ta=Q.xk,Fa=Q.Wk,Aa=Q.Gl,qa=[],ra=0,Pa=null,Qa=null,Ea=0,ca=0,fa=d(window.PR_TAB_WIDTH),Z=/([\r\n ]) /g,za=/(^| ) /gm,ha=/\r\n?|\n/g,ua=/[ \r\n]$/,ma=!0,Ua=window._pr_isIE6();Aa=Ua?Aa&&"PRE"===Aa.tagName?6===Ua?"&#160;\r\n":7===Ua?"&#160;<br />\r":8===Ua?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(Fa){var Vb=[];for(Ua=0;10>Ua;++Ua)Vb[Ua]=Aa+'</li><li class="L'+Ua+'">';var $d="number"===typeof Fa?Fa-1:0;qa.push('<ol class="linenums"><li class="L',$d%10,'"');$d&&
qa.push(' value="',$d+1,'"');qa.push(">");var Nl=function(){var Qe=Vb[++$d%10];return Pa?"</span>"+Qe+'<span class="'+Pa+'">':Qe}}else Nl=Aa;for(;;)if(Ea<na.length&&(ca<ta.length?na[Ea]<=ta[ca]:1))Y(na[Ea]),Pa&&(qa.push("</span>"),Pa=null),qa.push(na[Ea+1]),Ea+=2;else if(ca<ta.length)Y(ta[ca]),Qa=ta[ca+1],ca+=2;else break;Y(la.length);Pa&&qa.push("</span>");Fa&&qa.push("</li></ol>");Q.Qi=qa.join("")}function k(Q,Y){for(var la=Y.length;0<=--la;){var na=Y[la];Ka.hasOwnProperty(na)?"console"in window&&
console.warn("cannot override language handler %s",na):Ka[na]=Q}}function l(Q,Y){Q&&Ka.hasOwnProperty(Q)||(Q=/^\s*</.test(Y)?"default-markup":"default-code");return Ka[Q]}function m(Q){var Y=Q.Fl,la=Q.Ok;Q.Qi=Y;try{var na=Y.match(Oa);Y=[];var ta=0,Fa=[];if(na)for(var Aa=0,qa=na.length;Aa<qa;++Aa){var ra=na[Aa];if(1<ra.length&&"<"===ra.charAt(0)){if(!ob.test(ra))if(pb.test(ra))Y.push(ra.substring(9,ra.length-3)),ta+=ra.length-12;else if(ea.test(ra))Y.push("\n"),++ta;else if(0<=ra.indexOf("nocode")&&
ra.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var Pa=ra.match(ya)[2],Qa=1;var Ea=Aa+1;a:for(;Ea<qa;++Ea){var ca=na[Ea].match(ya);if(ca&&ca[2]===Pa)if("/"===ca[1]){if(0===--Qa)break a}else++Qa}Ea<qa?(Fa.push(ta,na.slice(Aa,Ea+1).join("")),Aa=Ea):Fa.push(ta,ra)}else Fa.push(ta,ra)}else{Qa=ra;var fa=Qa.indexOf("&");if(0>fa)var Z=Qa;else{for(--fa;0<=(fa=Qa.indexOf("&#",fa+1));){var za=Qa.indexOf(";",fa);if(0<=za){var ha=Qa.substring(fa+
3,za),ua=10;ha&&"x"===ha.charAt(0)&&(ha=ha.substring(1),ua=16);var ma=parseInt(ha,ua);isNaN(ma)||(Qa=Qa.substring(0,fa)+String.fromCharCode(ma)+Qa.substring(za+1))}}Z=Qa.replace(A,"<").replace(G,">").replace(V,"'").replace(K,'"').replace(U," ").replace(xa,"&")}Y.push(Z);ta+=Z.length}}var Ua=Y.join("");Q.source=Ua;Q.fk=0;Q.Vo=Fa;l(la,Ua)(Q);h(Q)}catch(Vb){"console"in window&&console.log(Vb&&Vb.stack?Vb.stack:Vb)}}var n=function(){for(var Q="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),
Y="(?:^^|[+-]",la=0;la<Q.length;++la)Y+="|"+Q[la].replace(/([^=<>:&a-z])/g,"\\$1");return Y+")\\s*"}(),t=/&/g,v=/</g,w=/>/g,z=/"/g,A=/&lt;/g,G=/&gt;/g,V=/&apos;/g,K=/&quot;/g,xa=/&amp;/g,U=/&nbsp;/g,ba=/[\r\n]/g,Na=null,Oa=RegExp("[^<]+|\x3c!--[\\s\\S]*?--\x3e|<!\\[CDATA\\[[\\s\\S]*?\\]\\]>|</?[a-zA-Z](?:[^>\"']|'[^']*'|\"[^\"]*\")*>|<","g"),ob=/^\x3c!--/,pb=/^<!\[CDATA\[/,ea=/^<br\b/i,ya=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,gb=g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),Ka={};k(gb,["default-code"]);k(f([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));k(f([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);k(f([],[["atv",/^[\s\S]+/]]),["uq.val"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));k(g({keywords:"null true false"}),["json"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);k(g({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);k(g({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);k(g({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);k(g({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);k(g({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);k(f([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(Q,Y,la){Q={Fl:Q,Ok:Y,Wk:la};m(Q);return Q.Qi};window.prettyPrint=function(Q){function Y(){for(var Qa=
window.PR_SHOULD_USE_CONTINUATION?qa.now()+250:Infinity;ra<na.length&&qa.now()<Qa;ra++){var Ea=na[ra];if(Ea.className&&0<=Ea.className.indexOf("prettyprint")){var ca=Ea.className.match(/\blang-(\w+)\b/);ca&&(ca=ca[1]);for(var fa=!1,Z=Ea.parentNode;Z;Z=Z.parentNode)if(("pre"===Z.tagName||"code"===Z.tagName||"xmp"===Z.tagName)&&Z.className&&0<=Z.className.indexOf("prettyprint")){fa=!0;break}if(!fa){Z=Ea;null===Na&&(fa=document.createElement("PRE"),fa.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
Na=!/</.test(fa.innerHTML));if(Na)if(fa=Z.innerHTML,"XMP"===Z.tagName)fa=a(fa);else{if("PRE"!==Z.tagName&&ba.test(fa)){var za="";Z.currentStyle?za=Z.currentStyle.whiteSpace:window.getComputedStyle&&(za=window.getComputedStyle(Z,null).whiteSpace);Z=!za||"pre"===za}else Z=!0;Z||(fa=fa.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{fa=[];for(Z=Z.firstChild;Z;Z=Z.nextSibling)b(Z,fa);fa=fa.join("")}fa=fa.replace(/(?:\r\n?|\n)$/,"");Z=Ea.className.match(/\blinenums\b(?::(\d+))?/);
Pa={Fl:fa,Ok:ca,Gl:Ea,Wk:Z?Z[1]&&Z[1].length?+Z[1]:!0:!1};m(Pa);if(Ea=Pa.Qi)if(ca=Pa.Gl,"XMP"===ca.tagName){fa=document.createElement("PRE");for(Z=0;Z<ca.attributes.length;++Z)za=ca.attributes[Z],za.specified&&("class"===za.name.toLowerCase()?fa.className=za.value:fa.setAttribute(za.name,za.value));fa.innerHTML=Ea;ca.parentNode.replaceChild(fa,ca)}else ca.innerHTML=Ea}}}ra<na.length?setTimeout(Y,250):Q&&Q()}for(var la=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),document.getElementsByTagName("xmp")],
na=[],ta=0;ta<la.length;++ta)for(var Fa=0,Aa=la[ta].length;Fa<Aa;++Fa)na.push(la[ta][Fa]);la=null;var qa=Date;qa.now||(qa={now:function(){return(new Date).getTime()}});var ra=0,Pa;Y()};window.PR={combinePrefixPatterns:c,createSimpleLexer:f,registerLangHandler:k,sourceDecorator:g,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[window.PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[window.PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[window.PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[window.PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[window.PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[window.PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[window.PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[window.PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],
[window.PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],[window.PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[window.PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[window.PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[window.PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[window.PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);
window.PR.registerLangHandler(window.PR.createSimpleLexer([],[[window.PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([],[[window.PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[window.PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\v\f\r "],[window.PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[window.PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[window.PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[window.PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[window.PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[window.PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[window.PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[window.PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],
[window.PR.PR_LITERAL,/^(?:true|false|null)\b/],[window.PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[window.PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[window.PR.PR_COMMENT,/^\/\/.*/],[window.PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[window.PR.PR_STRING,/'.'/],[window.PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[window.PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[window.PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[window.PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),
["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[window.PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[window.PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[window.PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[window.PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[window.PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[window.PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[window.PR.PR_LITERAL,
/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^[a-z_]\w*/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[window.PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[window.PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[window.PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);window.PR.registerLangHandler(window.PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[window.PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[window.PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[window.PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[window.PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[window.PR.PR_KEYWORD,
/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],[window.PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[window.PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[window.PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[window.PR.PR_PLAIN,
/^[$a-zA-Z_][\w$]*/],[window.PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[window.PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[window.PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[window.PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^[a-z_][\w-]*/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[window.PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[window.PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[window.PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[window.PR.PR_LITERAL,/^(?:true|false|nil)\b/,
null],[window.PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[window.PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[window.PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[window.PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[window.PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[window.PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[window.PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[window.PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[window.PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[window.PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[window.PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[window.PR.PR_PUNCTUATION,/^(?:\[|\])/]]),
["vb","vbs"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[window.PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[window.PR.PR_COMMENT,/^--[^\r\n]*/],[window.PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[window.PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[window.PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[window.PR.PR_LITERAL,
/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],[window.PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[window.PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[window.PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[window.PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[window.PR.PR_PLAIN,
/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[window.PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[window.PR.PR_TYPE,/^[&]\S+/,null,"&"],[window.PR.PR_TYPE,/^!\S*/,null,"!"],[window.PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[window.PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[window.PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[window.PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[window.PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],
[window.PR.PR_PUNCTUATION,/^-/],[window.PR.PR_KEYWORD,/^\w+:[ \r\n]/],[window.PR.PR_PLAIN,/^\w+/]]),["yaml","yml"]);var jP=window;var lP=function(a){a.C&&a.eventHandler.listen(a.C,"click",()=>void a.setAttribute("dark-code",""));a.D&&a.eventHandler.listen(a.D,"click",()=>void a.removeAttribute("dark-code"));a.h&&a.eventHandler.listen(a.h,"click",()=>void kP(a));a.o&&a.eventHandler.listen(a.o,"click",()=>{const b={title:a.getAttribute("jsfiddle-title")||"Code sample",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""},c=a.getAttribute("scope");c?_ds.xI(c,b):_ds.wI([a],b)})},kP=async function(a){var b=a.querySelector("pre:not(.devsite-copy-hide)");
if(b&&(b=[...b.childNodes],_ds.nq(document.body,b),a.v)){const c=new _ds.Ek;let d;null==(d=a.h)||d.setAttribute("aria-label","Code sample copied to clipboard");_ds.Ck(a.eventHandler,a.v,"transitionend",()=>{c.g()});await c.promise;_ds.Ck(a.eventHandler,a.v,"transitionend",()=>{let e;null==(e=a.h)||e.setAttribute("aria-label",a.G)})}},mP=class extends _ds.E{constructor(){super(["devsite-snackbar"]);this.v=this.D=this.o=this.C=this.h=this.g=null;this.F=!1;this.G="";this.eventHandler=new _ds.H;this.J=
new _ds.Ek;this.storage=new _ds.lm;this.H=new _ds.wE(_ds.AE(_ds.zE()));_ds.Tg(this,(0,_ds.u)`no-toggle`)}static get observedAttributes(){return["dark-code"]}whenReady(){return this.J.promise}async connectedCallback(){var a=await _ds.x();if(!this.F){var b=this.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))this.setAttribute("no-copy",
""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");this.setAttribute("data-copy-event-label",b.getAttribute("data-copy-event-label")||"");b.classList.remove("devsite-click-to-copy");var c=b.getAttribute("data-label");this.G=c?`${"Copy code sample"}: ${c}`:"Copy code sample";b.classList.contains("devsite-disable-code-toggle")&&(_ds.D(this,"no-toggle","",this),b.classList.remove("devsite-disable-code-toggle"))}if(b=this.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample"))this.setAttribute("js-fiddle",
""),b.classList.remove("devsite-enable-open-in-jsfiddle"),b.classList.add("devsite-jsfiddle-code-sample");if(this.hasAttribute("js-fiddle")&&b){c=["scope","jsfiddle-title","jsfiddle-wrap","jsfiddle-label"];for(var d of c)b.hasAttribute(`data-${d}`)&&(this.setAttribute(d,`${b.getAttribute(`data-${d}`)}`),b.removeAttribute(`data-${d}`))}this.prettyPrint();this.F=!0}if((d=this.querySelector(".devsite-dark-code-default"))||this.storage.get("pref_dark-code"))this.setAttribute("dark-code",""),d&&d.classList.remove("devsite-dark-code-default");
this.J.g();try{await a.intersectionEnterForElement(this)}catch(g){if("IntersectionObserver not supported"!==g.message)return}if(a=this.querySelector(".devsite-code-buttons-container"))this.g=a;else{this.g=_ds.N(eP);if(this.hasAttribute("scope")){this.o=_ds.N(iP,{label:"Open code sample in JSFiddle"});(this.hasAttribute("jsfiddle-label")||this.hasAttribute("jsfiddle-title"))&&this.o.setAttribute("data-label",`${this.getAttribute("jsfiddle-label")||this.getAttribute("jsfiddle-title")}`);var e;null==
(e=this.g)||e.appendChild(this.o)}if(!this.hasAttribute("no-toggle")){this.C=_ds.N(fP,{label:"Dark code theme"});var f;null==(f=this.g)||f.appendChild(this.C);this.D=_ds.N(gP,{label:"Light code theme"});let g;null==(g=this.g)||g.appendChild(this.D)}if(!this.hasAttribute("no-copy")){e=this.getAttribute("data-copy-event-label");f="Click To Copy";e&&(f+=`: ${e}`);this.h=_ds.N(hP,{label:this.G,Go:f});let g;null==(g=this.g)||g.appendChild(this.h)}this.prepend(this.g)}lP(this);this.v=document.querySelector("devsite-snackbar")}async disconnectedCallback(){(await _ds.x()).unregisterIntersectionForElement(this);
this.g&&this.removeChild(this.g);_ds.I(this.eventHandler)}prettyPrint(){var a=[...this.getElementsByClassName("prettyprint")];for(const c of a){c.classList.remove("prettyprint");var b=(a=c.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?a[1]:void 0;let d;a=c.innerHTML;b=null!=(d=b)?d:"";a=a.replace(/(&#39;)/g,"'");a=jP.prettyPrintOne(a,b,void 0);_ds.wc(c,this.H.g(a));c.getElementsByTagName("strong").length&&c.classList.add("devsite-code-highlight")}}async attributeChangedCallback(a,b,c){if("dark-code"===
a&&b!==c&&!this.querySelector(".devsite-dark-code-default"))if(this.hasAttribute("dark-code")){this.storage.set("pref_dark-code","1");await _ds.nj();var d=[...document.querySelectorAll("devsite-code:not([dark-code])")].filter(f=>f!==this);for(var e of d)e.setAttribute("dark-code","")}else{this.storage.remove("pref_dark-code");await _ds.nj();e=[...document.querySelectorAll("devsite-code[dark-code]")];for(d of e)d.removeAttribute("dark-code")}}};mP.prototype.attributeChangedCallback=mP.prototype.attributeChangedCallback;
mP.prototype.disconnectedCallback=mP.prototype.disconnectedCallback;mP.prototype.connectedCallback=mP.prototype.connectedCallback;mP.prototype.whenReady=mP.prototype.whenReady;try{window.customElements.define("devsite-code",mP)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
