(function(_ds){var window=this;var xP=function(a){return!a.classList.contains("material-icons")},FP=async function(a,b){await DevsiteApp.whenReady();const c=_ds.F();var d=DevsiteApp.getInsecureHost();b=b.Y;if(b.origin===c.origin||!d||b.origin===d){try{var e=_ds.Xe(_ds.yl,b.data)}catch(g){return}d=_ds.Fe(e,1,0);if(4===d)yP(a,b);else{var f=e.getName();if(f&&(f=a.querySelector(`devsite-iframe iframe[name="${f}"]`)))switch(d){case 5:zP(e,f);break;case 8:AP(b,e,c);break;case 1:BP(b,e,c);break;case 6:case 7:CP(d,c,e);break;case 9:DP(a,
e);break;case 10:EP(e,c)}}}},JP=function(a){a.o=a.querySelector(".devsite-article-body");a.o&&(GP(a),a.v=[]);a.g&&a.g.disconnect();a.h.clear();HP(a);if(!document.body.hasAttribute("appearance")){var b=[...a.querySelectorAll("picture > source.devsite-dark-theme")];for(var c of b){b=c.closest("picture");const d=b.querySelector("img");b.querySelectorAll("source:not(.devsite-dark-theme)").length?c.remove():b&&d&&b.replaceWith(d)}}c=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));
"docs"===document.body.getAttribute("layout")&&a.o&&(b=Array.from(a.o.querySelectorAll("h1, h2, h3, h4, h5, h6")),c.push(...b));a.h.clear();a.h=new Set(c);if(_ds.F().hash){c=new _ds.YF;for(const d of a.h)_ds.XF(c,d,xP)}else IP(a,a.h);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},HP=function(a){Array.from(a.getElementsByTagName("table")).forEach(b=>{if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=document.createElement("div");c.classList.add("devsite-table-wrapper");
b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));b.parentNode&&b.parentNode.insertBefore(c,b);c.appendChild(b)}})},yP=async function(a,b){const c=KP(a,b.source);if(c){const e="goog_"+_ds.Bh++;c.setAttribute("name",e);var d=_ds.zl(3);d=_ds.Ve(d,2,e);(b=b.source)&&b.postMessage(_ds.Ye(d),"*");(b=document.body.getAttribute("appearance"))&&LP(c,b);a.v.push(c)}},zP=async function(a,b){const c=_ds.Nh(document).y,d=_ds.Pe(a,4);a=_ds.Pe(a,
3);b=_ds.ai(b);d&&b.setAttribute("width",`${d}px`);a&&b.setAttribute("height",`${a}px`);window.requestAnimationFrame(()=>{window.scrollTo(_ds.Nh(document).x,c)})},AP=async function(a,b,c){b=_ds.Al(_ds.zl(8),_ds.y(b,8));c=_ds.Ve(b,6,c.toString());(a=a.source)&&a.postMessage(_ds.Ye(c),"*")},BP=async function(a,b,c){b=_ds.Al(_ds.zl(2),_ds.y(b,8));c=_ds.Ve(b,7,`${c.search}${c.hash}`);(a=a.source)&&a.postMessage(_ds.Ye(c),"*")},CP=async function(a,b,c){const d=c.Sa();b=new URL(c.getUrl(),b.origin);b=`${window.location.origin}${window.location.pathname}${b.search}${b.hash}`;
6===a?window.history.pushState({},d,b):window.history.replaceState({},d,b)},DP=async function(a,b){const c=_ds.y(b,9);let d;try{d=JSON.parse(_ds.y(b,10))}catch(e){console.warn("Event data from Framebox is not valid JSON.",a);return}"analyticsEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:d,bubbles:!0})):"cloudtrackEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:{eventData:d},bubbles:!0})):"devsite-apix"===c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",
{detail:d,bubbles:!0}))},EP=async function(a,b){if(a=a.getUrl()){const c=new URL(a,b.origin);a.startsWith("#")||b.origin===c.origin&&b.pathname===c.pathname&&b.search===c.search?DevsiteApp.scrollToAnchor(c.hash,!0):DevsiteApp.fetchPage(c.href)}},KP=function(a,b){let c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(d=>{_ds.bi(d)===b&&(c=d)});return c},LP=function(a,b){var c=_ds.zl(12);b=_ds.Ve(c,12,b);a&&a.contentWindow&&(a=a.contentWindow)&&a.postMessage(_ds.Ye(b),"*")},GP=function(a){"full"===
document.body.getAttribute("layout")&&(a=a.o.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&Array.from(a).forEach(b=>{b.removeAttribute("tabindex")})},IP=function(a,b){a.g&&b.forEach(c=>{a.g.observe(c)})},MP=class extends _ds.E{constructor(){super();this.C=new _ds.H;this.D=new _ds.H;this.h=new Set;this.v=[];this.g=null;"IntersectionObserver"in window&&(this.g=new IntersectionObserver(a=>{for(const b of a)b.isIntersecting&&
(a=b.target,_ds.XF(new _ds.YF,a,xP),this.h.delete(a),this.g.unobserve(a))},{rootMargin:"100%"}))}connectedCallback(){this.C.listen(window,"message",a=>FP(this,a));this.C.listen(document.body,"devsite-appearance-updated",a=>{if((a=a.Y.detail.yb)&&this.v.length)for(const b of this.v)LP(b,a)});JP(this)}disconnectedCallback(){this.g&&this.g.disconnect();this.h.clear();_ds.I(this.C);_ds.I(this.D)}kb(a){a&&([".devsite-article",".devsite-content-data","devsite-content-footer","devsite-notification"].forEach(b=>
{_ds.Wg(this,this.querySelector(b),a.querySelector(b))}),JP(this))}};MP.prototype.updateContent=MP.prototype.kb;MP.prototype.disconnectedCallback=MP.prototype.disconnectedCallback;MP.prototype.connectedCallback=MP.prototype.connectedCallback;try{window.customElements.define("devsite-content",MP)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
