(function(_ds){var window=this;var TZ=function(a){var b=a.qj;a=a.columns;let c='<div class="dropdown-tabbed-menu"><ul class="dropdown-tabbed-menu-list">';const d=a.length;for(let e=0;e<d;e++){const f=a[e];c+='<li class="dropdown-tabbed-menu-list-item"><a href="#" column-id="'+_ds.T(f.Do)+'" tabindex="0" track-type="nav" track-name="'+_ds.T(f.text)+'" track-metadata-eventdetail="#" track-metadata-position="nav - '+_ds.T(b)+'" track-metadata-module="secondary nav">'+_ds.R(f.text)+"</a></li>"}return(0,_ds.P)(c+"</ul></div>")},UZ=
function(a){var b=a.qj,c=a.href;a=a.text;return(0,_ds.P)('<div class="dropdown-tabbed-menu-button"><a href="'+_ds.T(_ds.W(c))+'" track-type="nav" track-name="'+_ds.T(a)+'" track-metadata-eventdetail="'+_ds.T(c)+'" track-metadata-position="nav - '+_ds.T(b)+'" track-metadata-module="secondary nav">'+_ds.R(a)+"</a></div>")};var VZ=function(a){a.o=Array.from(a.querySelectorAll("tab"));let b=a.querySelector(".devsite-tabs-wrapper");if(!b){b=a.ownerDocument.createElement("div");b.classList.add("devsite-tabs-wrapper");a.appendChild(b);var c;null==(c=a.o)||c.forEach(e=>{let f;return null==(f=b)?void 0:f.appendChild(e)})}a.v=b;a.appendChild(b);if(!a.hasAttribute("no-overflow")){c=a.ownerDocument.createElement("tab");_ds.D(a,"overflow-tab","",c);var d=a.ownerDocument.createElement("a");_ds.ih(d,"#");d.textContent="More";d.classList.add("devsite-icon");
d.classList.add("devsite-icon-arrow-drop-down");c.appendChild(d);a.g=c;d=a.ownerDocument.createElement("div");d.classList.add("devsite-tabs-overflow-menu");_ds.D(a,"scrollbars","",d);_ds.D(a,"hidden","",d);a.C=d;c.appendChild(d);b.appendChild(c)}},ZZ=function(a){let b;null==(b=a.o)||b.forEach(async(c,d)=>{if(await WZ(c)){var e=Array.from(c.querySelectorAll(".devsite-tabs-dropdown-column")),f=c.querySelector(".devsite-tabs-dropdown"),g=c.querySelector("a");e.forEach((h,k)=>{_ds.D(a,"column-id",`tab-${d}-column-${k}`,
h)});e=e.map(h=>{const k=h.querySelector(".devsite-nav-title")||h.querySelector(".devsite-nav-item-title");return{Do:h.getAttribute("column-id"),text:null==k?void 0:k.textContent}});g&&(g=_ds.N(TZ,{qj:(g.textContent||"").toLowerCase().trim(),columns:e}),f&&(e=c.querySelector(".devsite-tabs-dropdown-content")))&&(f.insertBefore(g,e),f=c.querySelector(".dropdown-tabbed-menu a"),XZ(c),a.eventHandler.listen(g,"click",h=>{h.preventDefault();const k=c.querySelector(".dropdown-tabbed-menu-button");h=h.target;
k&&h.tagName&&"a"===h.tagName.toLowerCase()&&!k.contains(h)&&YZ(a,c,(null==h?void 0:h.getAttribute("column-id"))||"")}),f&&YZ(a,c,f.getAttribute("column-id")||""))}})},$Z=function(a,b){if(!b)return 0;const c=[];let d=b;for(;d.parentElement&&0===d.offsetWidth;)c.push(d),_ds.D(a,"render-hidden","",d),d=d.parentElement;a=_ds.Tk(b).width;for(const e of c)e.removeAttribute("render-hidden");return a},i_=function(a){a.eventHandler.listen(document.body,"devsite-sticky-resize",()=>a.F.g());a.eventHandler.listen(a,
"click",c=>{if(!(c.shiftKey||c.ctrlKey||c.metaKey||c.altKey)){var d=c.target,e=a_(a,d);if(e)if(e===a.g)b_(a,c);else if(c_(a),d.classList.contains("devsite-tabs-dropdown-toggle"))c.preventDefault(),c.stopPropagation(),e.hasAttribute("dropdown--open")?d_(a):e_(a,e);else{var f;"A"===d.tagName?f=d:f=_ds.ki(d,"A");var g=e.querySelector(".devsite-tabs-dropdown");if(g&&g.contains(d))f&&f.hasAttribute("href")||(c.preventDefault(),c.stopPropagation());else{if(c=a.J||a.querySelector("[active]"))c.removeAttribute("active"),
_ds.D(a,"aria-selected","false",c);_ds.D(a,"active","",e);_ds.D(a,"aria-selected","true",e);a.J=e;f&&f&&"#"!==f.href||a.F.g()}}}});if(a.querySelector("tab[dropdown]")||a.querySelector("tab[overflow-tab]")){var b="onpointermove"in window?"pointerover":"mouseover";const c="onpointermove"in window?"pointerleave":"mouseleave",d=a.querySelectorAll("tab[clickable]");if(d.length){for(const e of d)a.eventHandler.listen(e,"click",f=>{const g=f.target,h=a_(a,g),k=null==h?void 0:h.querySelector(".devsite-tabs-dropdown");
if(k){let l;(null==(l=a.g)?0:l.contains(g))||k.contains(g)||(f.preventDefault(),f.stopPropagation(),(null==h?0:h.hasAttribute("dropdown--open"))?d_(a):f_(a,f))}});a.eventHandler.listen(document.body,"click",e=>{a.v&&!a.v.contains(e.target)&&d_(a)})}else a.eventHandler.listen(a,b,e=>void g_(a,e)),a.eventHandler.listen(a,c,()=>void h_(a))}b=[...a.querySelectorAll(".devsite-tabs-close-button")];for(const c of b)a.eventHandler.listen(c,"click",()=>d_(a))},j_=function(a){_ds.D(a,"hidden","",a.g);if(!(a.o&&
3>a.o.length)){var b=$Z(a,a);if(0!==b){var c,d=(null==(c=a.o)?void 0:c.slice())||[],e=0,f;d.forEach(k=>{k.parentNode!==a.v&&(f?f.parentNode&&f.parentNode.insertBefore(k,f.nextSibling):_ds.Th(a.v,k,0));f=k;e+=$Z(a,k)});if(!(e<=b)){c=a.H;var g;null==(g=a.g)||g.removeAttribute("hidden");(g=a.querySelector("[active]"))&&(c+=$Z(a,g));for(var h;null==(h=d)?0:h.length;){const k=d.shift();if(k===g)continue;const l=$Z(a,k||null);if(c+l<=b)c+=l;else{let m;null==(m=a.C)||m.appendChild(k)}}}}}},g_=async function(a,
b){(await _ds.x()).isTouchEnabled()||f_(a,b)},h_=async function(a){(await _ds.x()).isTouchEnabled()||d_(a,300)},d_=function(a,b=0){_ds.I(a.h);window.clearTimeout(a.D);const c=a.querySelector("tab[dropdown--open]");if(c){const d=c.querySelector(".devsite-tabs-dropdown");_ds.D(a,"dropdown-transition","",d);_ds.Bk(a.h,d,_ds.lf,()=>{null==d||d.removeAttribute("dropdown-transition");a.removeAttribute("dropdown--open");_ds.D(a,"hidden","",d)});a.D=window.setTimeout(()=>{c.removeAttribute("dropdown--open");
k_(a,c)},b)}else a.removeAttribute("dropdown--open");c_(a)},a_=function(a,b){for(;b&&b!==a;){if("TAB"===b.tagName.toUpperCase())return b;b=b.parentElement}return null},f_=function(a,b){const c=b.target,d=a_(a,c);if(d){let e;d===a.g||(null==(e=a.g)?0:e.contains(c))?b_(a,b):e_(a,d)}},b_=async function(a,b){b.preventDefault();b.stopPropagation();document.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs"));await _ds.mj();if(!a.hasAttribute("overflow-menu--open")){b=await _ds.x();await b.whenReady();
if(b.isTouchEnabled()){const d=e=>{a.contains(e.target)||c_(a);_ds.Ck(a.h,document.body,["devsite-close-overflow-tabs","click"],d)};a.h.listen(document.body,["devsite-close-overflow-tabs","click"],d)}var c;null==(c=a.C)||c.removeAttribute("hidden");_ds.D(a,"overflow-menu--open","")}},e_=async function(a,b){c_(a);if(b.hasAttribute("dropdown")){if(_ds.I(a.h),window.clearTimeout(a.D),!b.hasAttribute("dropdown--open")){(await _ds.x()).isTouchEnabled()&&_ds.Bk(a.h,document.body,"click",g=>{a.contains(g.target)||
d_(a)});var c=a.querySelector("tab[dropdown--open]"),d=b.querySelector(".devsite-tabs-dropdown");if(d){d.removeAttribute("hidden");_ds.Hk(d,"left","");var e=_ds.Kh(window||window),f=Array.from(d.querySelectorAll(".devsite-tabs-dropdown-column"));if(!b.hasAttribute("dropdown-full")&&1<f.length){const g=[];f.forEach(k=>{g.push(k.scrollWidth)});const h=Math.max.apply(null,g);h*f.length<e.width?f.forEach(k=>{_ds.Hk(k,"width",`${h}px`)}):_ds.D(a,"dropdown-full","",b)}f=d.getBoundingClientRect();b.hasAttribute("dropdown-full")?
_ds.Hk(d,"left",`-${f.left}px`):(e=Math.min(f.left,f.left+f.width-e.width),0<e&&_ds.Hk(d,"left",`-${e}px`));c?(c.removeAttribute("dropdown--open"),k_(a,c),c=c.querySelector(".devsite-tabs-dropdown"),null==c||c.removeAttribute("dropdown-transition"),_ds.D(a,"hidden","",c)):(_ds.D(a,"dropdown-transition","",d),_ds.Bk(a.h,d,_ds.lf,()=>d.removeAttribute("dropdown-transition")));window.requestAnimationFrame(()=>{_ds.D(a,"dropdown--open","");_ds.D(a,"dropdown--open","",b);k_(a,b)})}else c&&(c.removeAttribute("dropdown--open"),
k_(a,c))}}else d_(a)},k_=function(a,b){_ds.D(a,"aria-expanded",`${b.hasAttribute("dropdown--open")}`,b.querySelector(".devsite-tabs-dropdown-toggle"))},c_=function(a){_ds.D(a,"hidden","",a.C);a.removeAttribute("overflow-menu--open")},WZ=async function(a){return(await _ds.x()).isTouchEnabled()||!a.hasAttribute("generated-tab-menu")?!1:!0},XZ=function(a){var b=a.querySelector(".dropdown-tabbed-menu-button-target");if(!a.querySelector(".dropdown-tabbed-menu-button")&&b){var c=a.querySelector("a");c&&
(c=c.textContent,b=b.querySelector(".devsite-nav-item a"),a=a.querySelector(".dropdown-tabbed-menu"),b&&(c=_ds.N(UZ,{qj:(c||"").toLowerCase().trim(),href:b.getAttribute("href")||"",text:b.textContent||""}),null==a||a.appendChild(c)))}},YZ=function(a,b,c){var d=Array.from(b.querySelectorAll(".devsite-tabs-dropdown-column"));b=Array.from(b.querySelectorAll(".dropdown-tabbed-menu a"));b.forEach(e=>e.removeAttribute("active"));d.forEach(e=>_ds.D(a,"hidden","",e));b=b.find(e=>e.getAttribute("column-id")===
c);d=d.find(e=>e.getAttribute("column-id")===c);b&&d&&(_ds.D(a,"active","",b),d.removeAttribute("hidden"))},l_=class extends _ds.E{constructor(){super();this.eventHandler=new _ds.H;this.h=new _ds.H;this.F=new _ds.xk(()=>{j_(this)},20);this.J=null;this.G=!1;this.D=0;this.C=this.g=null;this.H=0;this.o=[];this.v=null;_ds.Sg(this,this.j`active`,this.j`aria-expanded`,this.j`aria-selected`,this.j`collapsed`,this.j`column-id`,this.j`connected`,this.j`dropdown`,this.j`dropdown-full`,this.j`dropdown--open`,
this.j`dropdown-transition`,this.j`hidden`,this.j`no-overflow`,this.j`overflow-menu--open`,this.j`overflow-tab`,this.j`render-hidden`,this.j`scrollbars`)}disconnectedCallback(){_ds.I(this.eventHandler);_ds.I(this.h)}connectedCallback(){this.G||(VZ(this),this.G=!0);_ds.D(this,"connected","");if(!this.hasAttribute("no-overflow")){_ds.D(this,"collapsed","",this.g);this.H=$Z(this,this.g);var a;null==(a=this.g)||a.removeAttribute("collapsed");i_(this);j_(this)}ZZ(this)}};
l_.prototype.connectedCallback=l_.prototype.connectedCallback;l_.prototype.disconnectedCallback=l_.prototype.disconnectedCallback;try{window.customElements.define("devsite-tabs",l_)}catch(a){console.warn("devsite.app.customElement.DevsiteTabs",a)};})(_ds_www);
