(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var f=this||self,m=function(a,b){a=a.split(".");var c=f;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b},n=function(a){return a};var p=new Map([]);p.set("devsite-a11y-announce",{src:"/android/js/devsite_devsite_a11y_announce_module.js"});p.set("devsite-analytics",{src:"/android/js/devsite_devsite_analytics_module.js"});p.set("devsite-analytics-scope",{src:"/android/js/devsite_devsite_analytics_scope_module.js"});p.set("devsite-anselm",{src:"/android/js/devsite_devsite_anselm_module.js"});p.set("devsite-api-getstarted",{src:"/android/js/devsite_devsite_api_getstarted_module.js"});p.set("devsite-apix",{src:"/android/js/devsite_devsite_apix_module.js"});
p.set("devsite-apix-index",{src:"/android/js/devsite_devsite_apix_index_module.js"});p.set("devsite-apix-snippets",{src:"/android/js/devsite_devsite_apix_snippets_module.js"});p.set("devsite-appearance-selector",{src:"/android/js/devsite_devsite_appearance_selector_module.js"});p.set("devsite-badger",{src:"/android/js/devsite_devsite_badger_module.js"});p.set("devsite-badge-awarded",{src:"/android/js/devsite_devsite_badge_awarded_module.js"});p.set("devsite-badge-awarder",{src:"/android/js/devsite_devsite_badge_awarder_module.js"});
p.set("devsite-badge-redeemer",{src:"/android/js/devsite_devsite_badge_redeemer_module.js"});p.set("devsite-book-nav",{src:"/android/js/devsite_devsite_book_nav_module.js"});p.set("devsite-bookmark",{src:"/android/js/devsite_devsite_bookmark_module.js"});p.set("devsite-carousel",{src:"/android/js/devsite_devsite_carousel_module.js"});p.set("devsite-catalog",{src:"/android/js/devsite_devsite_catalog_module.js"});p.set("devsite-catalog-body-badges",{src:"/android/js/devsite_devsite_catalog_body_badges_module.js"});
p.set("devsite-chart",{src:"/android/js/devsite_devsite_chart_module.js"});p.set("devsite-checkbox",{src:"/android/js/devsite_devsite_checkbox_module.js"});p.set("devsite-code",{src:"/android/js/devsite_devsite_code_module.js"});p.set("devsite-content",{src:"/android/js/devsite_devsite_content_module.js"});p.set("devsite-codelab-catalog",{src:"/android/js/devsite_devsite_codelab_catalog_module.js"});p.set("devsite-credentials-dialog",{src:"/android/js/devsite_devsite_credentials_dialog_module.js"});
p.set("devsite-cse",{src:"/android/js/devsite_devsite_cse_module.js"});p.set("devsite-device",{src:"/android/js/devsite_devsite_device_module.js"});p.set("devsite-devprofile",{src:"/android/js/devsite_devsite_devprofile_module.js"});p.set("devsite-dialog",{src:"/android/js/devsite_devsite_dialog_module.js"});p.set("devsite-dropdown-list",{src:"/android/js/devsite_devsite_dropdown_list_module.js"});p.set("devsite-dynamic-content",{src:"/android/js/devsite_devsite_dynamic_content_module.js"});
p.set("devsite-expandable",{src:"/android/js/devsite_devsite_expandable_module.js"});p.set("devsite-extradory",{src:"/android/js/devsite_devsite_extradory_module.js"});p.set("devsite-feature-tooltip",{src:"/android/js/devsite_devsite_feature_tooltip_module.js"});p.set("devsite-feedback",{src:"/android/js/devsite_devsite_feedback_module.js"});p.set("devsite-filter",{src:"/android/js/devsite_devsite_filter_module.js"});p.set("devsite-footer-linkboxes",{src:"/android/js/devsite_devsite_footer_linkboxes_module.js"});
p.set("devsite-footer-promos",{src:"/android/js/devsite_devsite_footer_promos_module.js"});p.set("devsite-footer-utility",{src:"/android/js/devsite_devsite_footer_utility_module.js"});p.set("devsite-googler-buttons",{src:"/android/js/devsite_devsite_googler_buttons_module.js"});p.set("devsite-hats-survey",{src:"/android/js/devsite_devsite_hats_survey_module.js"});p.set("devsite-header",{src:"/android/js/devsite_devsite_header_module.js"});p.set("devsite-heading-link",{src:"/android/js/devsite_devsite_heading_link_module.js"});
p.set("devsite-iframe",{src:"/android/js/devsite_devsite_iframe_module.js"});p.set("devsite-info-popout",{src:"/android/js/devsite_devsite_info_popout_module.js"});p.set("devsite-jump-to",{src:"/android/js/devsite_devsite_jump_to_module.js"});p.set("devsite-jsfiddle-button",{src:"/android/js/devsite_devsite_jsfiddle_button_module.js"});p.set("devsite-language-selector",{src:"/android/js/devsite_devsite_language_selector_module.js"});p.set("devsite-lightbox",{src:"/android/js/devsite_devsite_lightbox_module.js"});
p.set("devsite-mathjax",{src:"/android/js/devsite_devsite_mathjax_module.js"});p.set("devsite-mdc",{src:"/android/js/devsite_devsite_mdc_module.js"});p.set("devsite-mwc",{src:"/android/js/devsite_devsite_mwc_module.js"});p.set("devsite-multiple-choice",{src:"/android/js/devsite_devsite_multiple_choice_module.js"});p.set("devsite-nav-buttons",{src:"/android/js/devsite_devsite_nav_buttons_module.js"});p.set("devsite-notification",{src:"/android/js/devsite_devsite_notification_module.js"});
p.set("devsite-pagination",{src:"/android/js/devsite_devsite_pagination_module.js"});p.set("devsite-panel",{src:"/android/js/devsite_devsite_panel_module.js"});p.set("devsite-playlist",{src:"/android/js/devsite_devsite_playlist_module.js"});p.set("devsite-playlist-earnable-badges",{src:"/android/js/devsite_devsite_playlist_earnable_badges_module.js"});p.set("devsite-playlist-summary",{src:"/android/js/devsite_devsite_playlist_summary_module.js"});p.set("devsite-product-catalog",{src:"/android/js/devsite_devsite_product_catalog_module.js"});
p.set("devsite-profile-card",{src:"/android/js/devsite_devsite_profile_card_module.js"});p.set("devsite-progress",{src:"/android/js/devsite_devsite_progress_module.js"});p.set("devsite-quiz",{src:"/android/js/devsite_devsite_quiz_module.js"});p.set("devsite-recommendations",{src:"/android/js/devsite_devsite_recommendations_module.js"});p.set("devsite-recommendations-dropdown",{src:"/android/js/devsite_devsite_recommendations_dropdown_module.js"});p.set("devsite-recommendations-sidebar",{src:"/android/js/devsite_devsite_recommendations_sidebar_module.js"});
p.set("devsite-recommended-content",{src:"/android/js/devsite_devsite_recommended_content_module.js"});p.set("devsite-reference-results",{src:"/android/js/devsite_devsite_reference_results_module.js"});p.set("devsite-rich-tooltip",{src:"/android/js/devsite_devsite_rich_tooltip_module.js"});p.set("devsite-search",{src:"/android/js/devsite_devsite_search_module.js"});p.set("devsite-select",{src:"/android/js/devsite_devsite_select_module.js"});p.set("devsite-selector",{src:"/android/js/devsite_devsite_selector_module.js"});
p.set("devsite-shell",{src:"/android/js/devsite_devsite_shell_module.js"});p.set("devsite-shell-activate-button",{src:"/android/js/devsite_devsite_shell_activate_button_module.js"});p.set("devsite-sitemask",{src:"/android/js/devsite_devsite_sitemask_module.js"});p.set("devsite-snackbar",{src:"/android/js/devsite_devsite_snackbar_module.js"});p.set("devsite-sort",{src:"/android/js/devsite_devsite_sort_module.js"});p.set("devsite-spinner",{src:"/android/js/devsite_devsite_spinner_module.js"});
p.set("devsite-support-form",{src:"/android/js/devsite_devsite_support_form_module.js"});p.set("devsite-tabs",{src:"/android/js/devsite_devsite_tabs_module.js"});p.set("devsite-thumb-rating",{src:"/android/js/devsite_devsite_thumb_rating_module.js"});p.set("devsite-toc",{src:"/android/js/devsite_devsite_toc_module.js"});p.set("devsite-topic",{src:"/android/js/devsite_devsite_topic_module.js"});p.set("devsite-tooltip",{src:"/android/js/devsite_devsite_tooltip_module.js"});
p.set("devsite-tracking-question",{src:"/android/js/devsite_devsite_tracking_question_module.js"});p.set("devsite-user",{src:"/android/js/devsite_devsite_user_module.js"});p.set("devsite-var",{src:"/android/js/devsite_devsite_var_module.js"});p.set("devsite-version-selector",{src:"/android/js/devsite_devsite_version_selector_module.js"});p.set("devsite-video",{src:"/android/js/devsite_devsite_video_module.js"});p.set("devsite-visibility-analytics",{src:"/android/js/devsite_devsite_visibility_analytics_module.js"});
p.set("devsite-vplus",{src:"/android/js/devsite_devsite_vplus_module.js"});p.set("devsite-wall-acknowledgement",{src:"/android/js/devsite_devsite_wall_acknowledgement_module.js"});p.set("devsite-youtube",{src:"/android/js/devsite_devsite_youtube_module.js"});p.set("google-codelab",{src:"/android/js/devsite_google_codelab_module.js"});p.set("google-codelab-about",{src:"/android/js/devsite_google_codelab_about_module.js"});p.set("google-codelab-analytics",{src:"/android/js/devsite_google_codelab_analytics_module.js"});
p.set("google-codelab-step",{src:"/android/js/devsite_google_codelab_step_module.js"});p.set("google-codelab-survey",{src:"/android/js/devsite_google_codelab_survey_module.js"});p.set("android-codelab-grader",{src:"/android/js/devsite_android_codelab_grader_module.js"});p.set("android-fully-clickable",{src:"/android/js/devsite_android_fully_clickable_module.js"});p.set("android-samples",{src:"/android/js/devsite_android_samples_module.js"});p.set("android-sticky-lesson",{src:"/android/js/devsite_android_sticky_lesson_module.js"});
p.set("android-sticky-toc",{src:"/android/js/devsite_android_sticky_toc_module.js"});m("DevsiteAppAuthorizedElements",p);m("DevsiteAppTenantCustomized",!0);var q={vc:0,uc:1,Wb:6,Ub:8,dc:12,ec:14,fc:17,kc:18,mc:21,oc:25,ta:37,pc:38,Fa:40,mb:45,ba:47,H:50,T:52,O:62,Ua:63,Ob:66,Eb:70,J:73,sb:74,da:75,Lb:76,Qa:77,Sa:80,P:81,hb:82,Na:83,Cb:85,ka:87,Ia:89,Gb:90,Ja:91,Ra:92,Z:93,sc:94,Ma:95,Y:96,Pb:97,K:98,M:99,nc:100,Ea:101,Oa:102,Kb:103,rc:104,oa:105,aa:106,Ca:107,ra:108,yb:109,la:110,za:111,qc:112,Mb:113,sa:114,W:115,va:116,kb:117,gb:118,Ka:119,Fb:120,ac:121,Nb:122,ic:123,Vb:124,bb:125,tb:126,Da:127,bc:128,ob:129,pb:130,ya:131,Za:132,L:133,Va:134,Ga:135,
lb:136,N:137,tc:138,vb:139,Yb:140,Tb:141,nb:142,eb:143,wb:144,V:145,rb:146,Wa:147,cb:148,Hb:149,qa:150,ja:151,Xa:152,xa:154,ca:155,lc:156,jc:157,Ta:158,wa:159,R:160,ea:161,pa:162,Zb:163,Jb:164,ua:165,ha:166,Qb:167,ia:168,ab:169,Ya:170,La:171,Ba:172,Ib:173,qb:174,zb:175,Ab:176,ub:177,Bb:178,Xb:179,hc:180,fa:181,na:182,X:183,I:184,Db:185,Pa:186,ib:187,ga:188,ma:189,jb:190,S:191,U:192,fb:193,Rb:194,Ha:195,xb:196,Aa:197,Sb:198,cc:199};const aa=Array.prototype.every?function(a,b){return Array.prototype.every.call(a,b,void 0)}:function(a,b){const c=a.length,d="string"===typeof a?a.split(""):a;for(let e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0};var t={},u=null,ba=function(a){var b;void 0===b&&(b=0);if(!u){u={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var g=c.concat(d[e].split(""));t[e]=g;for(var h=0;h<g.length;h++){var k=g[h];void 0===u[k]&&(u[k]=h)}}}b=t[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=g=0;g<a.length-2;g+=3){var l=a[g],r=a[g+1];k=a[g+2];h=b[l>>2];l=b[(l&3)<<4|r>>4];r=b[(r&15)<<2|k>>6];k=b[k&63];c[e++]=""+h+l+r+k}h=0;k=d;switch(a.length-
g){case 2:h=a[g+1],k=b[(h&15)<<2]||d;case 1:a=a[g],c[e]=""+b[a>>2]+b[(a&3)<<4|h>>4]+k+d}return c.join("")};var v="undefined"!==typeof Uint8Array,ca={};let da;var w=class{constructor(a){if(ca!==ca)throw Error("illegal external caller");this.G=a;if(null!=a&&0===a.length)throw Error("ByteString should be constructed with non-empty values");}};const x="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function y(a,b){Object.isFrozen(a)||(x?a[x]|=b:void 0!==a.o?a.o|=b:Object.defineProperties(a,{o:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}function z(a){let b;x?b=a[x]:b=a.o;return null==b?0:b}function A(a){y(a,1);return a}function B(a){return Array.isArray(a)?!!(z(a)&2):!1}function C(a){if(!Array.isArray(a))throw Error("cannot mark non-array as immutable");y(a,2)}
function D(a,b){if(!Array.isArray(a))throw Error("cannot mark non-array as mutable");b?y(a,8):Object.isFrozen(a)||(x?a[x]&=-9:void 0!==a.o&&(a.o&=-9))};function E(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}let F;var G=Object.freeze(A([])),H=function(a){if(B(a.i))throw Error("Cannot mutate an immutable Message");},ea="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;function fa(a){return{value:a,configurable:!1,writable:!1,enumerable:!1}};function ha(a,b){if(Array.isArray(a))return new b(a)};function ia(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)){if(v&&null!=a&&a instanceof Uint8Array)return ba(a);if(a instanceof w){var b=a.G;b=null==b||"string"===typeof b?b:v&&b instanceof Uint8Array?ba(b):null;return null==b?"":a.G=b}}}return a};function I(a,b=ja){return ka(a,b)}function la(a,b){if(null!=a){if(Array.isArray(a))a=ka(a,b);else if(E(a)){const c={};for(let d in a)c[d]=la(a[d],b);a=c}else a=b(a);return a}}function ka(a,b){const c=a.slice();for(let d=0;d<c.length;d++)c[d]=la(c[d],b);Array.isArray(a)&&z(a)&1&&A(c);return c}function ma(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a=ia(a);return Array.isArray(a)?I(a,ma):a}
function ja(a){if("object"===typeof a){if(v&&null!=a&&a instanceof Uint8Array)return new Uint8Array(a);if(Array.isArray(a.i)&&a.constructor!==Object){var b;J=b=I(a.i);b=new a.constructor(b);J=null;K(b,a);return b}}return a};var L=function(a){return a.h||(a.h=a.i[a.j+a.m]={})},M=function(a,b,c=!1){return-1===b?null:b>=a.j?a.h?a.h[b]:void 0:c&&a.h&&(c=a.h[b],null!=c)?c:a.i[b+a.m]},N=function(a,b,c,d=!1){H(a);if(b>=a.j||d)L(a)[b]=c;else{if(void 0!==a.h&&a.j>=a.i.length){d=a.i.length-1;const e=b+a.m;e>=d?(a.i[d]=void 0,a.i[e]=c,a.i.push(a.h)):a.i[e]=c}else a.i[b+a.m]=c;void 0!==a.h&&b in a.h&&delete a.h[b]}},O=function(a,b,c=!0,d){let e=M(a,b,d);Array.isArray(e)||(e=G);if(B(a.i))c&&(C(e),Object.freeze(e));else if(e===G||
B(e))e=A(e.slice()),N(a,b,e,d);return e},na=function(a,b){a=M(a,b);a=null==a?a:!!a;return null==a?!1:a};function oa(a){H(a);N(a,2,"en")}
var pa=function(a,b,c,d=!1){{a.g||(a.g={});const e=a.g[c];if(e)b=e;else if(b=ha(M(a,c,d),b))a.g[c]=b,B(a.i)&&C(b.i)}if(null==b)return b;B(b.i)&&!B(a.i)&&(b=b.F(),N(a,c,b.i,d),a.g[c]=b);return b},qa=function(a,b,c,d,e=!0){a.g||(a.g={});var g=B(a.i);let h=a.g[c];d=O(a,c,!0,d);const k=g||B(d);if(!h){h=[];g=g||k;for(let r=0;r<d.length;r++){var l=d[r];g=g||B(l);l=ha(l,b);void 0!==l&&(h.push(l),k&&C(l.i))}a.g[c]=h;D(d,!g)}b=k||e;e=B(h);b&&!e&&(Object.isFrozen(h)&&(a.g[c]=h=h.slice()),C(h),Object.freeze(h));
!b&&e&&(a.g[c]=h=h.slice());return h},ra=function(a,b,c,d=!1){const e=B(a.i);b=qa(a,b,c,d,e);a=O(a,c,d);if(!(c=e)&&(c=a)){if(!Array.isArray(a))throw Error("cannot check mutability state of non-array");c=!(z(a)&8)}if(c){for(c=0;c<b.length;c++)(d=b[c])&&B(d.i)&&!e&&(b[c]=b[c].F(),a[c]=b[c].i);D(a,!0)}return b},P=function(a,b){a=M(a,b);return null==a?"":a};var ta=function(){var a=Q.g;F=!0;try{return JSON.stringify(a.toJSON(),sa)}finally{F=!1}},ua=class{constructor(a,b,c){a||(a=J);J=null;var d=this.constructor.g||0,e=0<d;let g=this.constructor.h;a||(a=g?[g]:[]);e&&0<a.length&&E(a[a.length-1])&&"g"in a[a.length-1]&&(d=0);this.m=(g?0:-1)-d;this.g=void 0;this.i=a;a:{d=this.i.length;a=d-1;if(d&&(d=this.i[a],E(d))){this.h=d;b=Object.keys(d);0<b.length&&aa(b,isNaN)?this.j=Number.MAX_VALUE:this.j=a-this.m;break a}void 0!==b&&-1<b?(this.j=Math.max(b,a+1-this.m),
this.h=void 0):this.j=Number.MAX_VALUE}if(!e&&this.h&&"g"in this.h)throw Error('Unexpected "g" flag in sparse object of message that is not a group type.');if(c)for(e=0;e<c.length;e++)b=c[e],b<this.j?(b+=this.m,(a=this.i[b])?Array.isArray(a)&&A(a):this.i[b]=G):(a=L(this),(d=a[b])?Array.isArray(d)&&A(d):a[b]=G)}toJSON(){const a=this.i;return F?a:I(a,ma)}};ua.prototype.toString=function(){return this.i.toString()};function sa(a,b){return ia(b)}
function K(a,b){b.A&&(a.A=b.A.slice());const c=b.g;if(c){b=b.h;for(let g in c){const h=c[g];if(h){var d=!(!b||!b[g]),e=+g;if(Array.isArray(h)){if(h.length)for(d=ra(a,h[0].constructor,e,d),e=0;e<Math.min(d.length,h.length);e++)K(d[e],h[e])}else(d=pa(a,h.constructor,e,d))&&K(d,h)}}}}let J;var va=class extends ua{F(){return this}};ea&&Object.defineProperties(va,{[Symbol.hasInstance]:fa(()=>{throw Error("Cannot perform instanceof checks for MutableMessage");})});function wa(a,b,c,d,e,g){if(a=a.g&&a.g[c])if(Array.isArray(a)){e=g.v?A(a.slice()):a;H(b);if(null!=e){g=A([]);d=!1;for(a=0;a<e.length;a++)g[a]=e[a].i,d=d||B(g[a]);b.g||(b.g={});b.g[c]=e;D(g,!d)}else b.g&&(b.g[c]=void 0),g=G;N(b,c,g)}else e=a,H(b),b.g||(b.g={}),null==e?g=e=void 0:g=e.i,b.g[c]=e,N(b,c,g);else v&&d instanceof Uint8Array?e=d.length?new w(new Uint8Array(d)):da||(da=new w(null)):(Array.isArray(d)&&(e?C(d):Array.isArray(d)&&z(d)&1&&g.v&&(d=d.slice())),e=d),N(b,c,e)};class xa extends va{F(){if(B(this.i)){var {v:a}={v:!0};a={v:a};const c=B(this.i);if(c&&!a.v)throw Error("copyRepeatedFields must be true for frozen messages");const d=new this.constructor;this.A&&(d.A=this.A.slice());const e=this.i;for(let g=0;g<e.length;g++){const h=e[g];if(g===e.length-1&&E(h))for(b in h){const k=+b;Number.isNaN(k)?L(d)[b]=h[b]:wa(this,d,k,h[b],c,a)}else wa(this,d,g-this.m,h,c,a)}var b=d}else b=this;return b}}ea&&Object.defineProperties(xa,{[Symbol.hasInstance]:fa(Object[Symbol.hasInstance])});var za=function(){var a=`${GoogleDevelopersObject}`.replace("\n","");var b=ya;if(null==a||""==a)b=new b;else{a=JSON.parse(a);if(!Array.isArray(a))throw b=typeof a,Error("Expected to deserialize an Array but got "+("object"!=b?b:a?Array.isArray(a)?"array":b:"null")+": "+a);J=a;b=new b(a);J=null}return b},ya=class extends xa{constructor(a){super(a,-1,Aa)}getTenantId(){let a=M(this,1);return null==a?0:a}getLocale(){return P(this,2)}getInsecureHost(){return P(this,7)}},Aa=[10,12,13,21,22];/*

 SPDX-License-Identifier: Apache-2.0
*/
var R;var S=class{constructor(a,b){this.g=b===Ba?a:""}toString(){return this.g+""}},Ba={};var Ca=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),Da=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var g=a[c].substring(0,d);e=a[c].substring(d+1)}else g=a[c];b(g,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var T=function(a){this.l=this.C=this.j="";this.B=null;this.s=this.u="";this.g=!1;if(a instanceof T){this.g=a.g;Ea(this,a.j);this.C=a.C;this.l=a.l;Fa(this,a.B);this.u=a.u;var b=a.h;var c=new U;c.j=b.j;b.g&&(c.g=new Map(b.g),c.h=b.h);Ga(this,c);this.s=a.s}else a&&(b=String(a).match(Ca))?(this.g=!1,Ea(this,b[1]||"",!0),this.C=V(b[2]||""),this.l=V(b[3]||"",!0),Fa(this,b[4]),this.u=V(b[5]||"",!0),Ga(this,b[6]||"",!0),this.s=V(b[7]||"")):(this.g=!1,this.h=new U(null,this.g))};
T.prototype.toString=function(){var a=[],b=this.j;b&&a.push(W(b,Ha,!0),":");var c=this.l;if(c||"file"==b)a.push("//"),(b=this.C)&&a.push(W(b,Ha,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.B,null!=c&&a.push(":",String(c));if(c=this.u)this.l&&"/"!=c.charAt(0)&&a.push("/"),a.push(W(c,"/"==c.charAt(0)?Ia:Ja,!0));(c=this.h.toString())&&a.push("?",c);(c=this.s)&&a.push("#",W(c,Ka));return a.join("")};
var Ea=function(a,b,c){a.j=c?V(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))},Fa=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.B=b}else a.B=null},Ga=function(a,b,c){b instanceof U?(a.h=b,La(a.h,a.g)):(c||(b=W(b,Ma)),a.h=new U(b,a.g))},Na=function(a){return a instanceof T?new T(a):new T(a)},V=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},W=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Oa),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},Oa=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Ha=/[#\/\?@]/g,Ja=/[#\?:]/g,Ia=/[#\?]/g,Ma=/[#\?@]/g,Ka=/#/g,U=function(a,b){this.h=this.g=null;this.j=a||null;this.l=!!b},X=function(a){a.g||(a.g=new Map,a.h=0,a.j&&Da(a.j,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};U.prototype.add=function(a,b){X(this);this.j=null;a=Y(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};
var Pa=function(a,b){X(a);b=Y(a,b);a.g.has(b)&&(a.j=null,a.h-=a.g.get(b).length,a.g.delete(b))},Qa=function(a,b){X(a);b=Y(a,b);return a.g.has(b)};U.prototype.forEach=function(a,b){X(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};var Ra=function(a,b){X(a);let c=[];if("string"===typeof b)Qa(a,b)&&(c=c.concat(a.g.get(Y(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};
U.prototype.set=function(a,b){X(this);this.j=null;a=Y(this,a);Qa(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};U.prototype.get=function(a,b){if(!a)return b;a=Ra(this,a);return 0<a.length?String(a[0]):b};
U.prototype.toString=function(){if(this.j)return this.j;if(!this.g)return"";const a=[],b=Array.from(this.g.keys());for(var c=0;c<b.length;c++){var d=b[c];const g=encodeURIComponent(String(d)),h=Ra(this,d);for(d=0;d<h.length;d++){var e=g;""!==h[d]&&(e+="="+encodeURIComponent(String(h[d])));a.push(e)}}return this.j=a.join("&")};
var Y=function(a,b){b=String(b);a.l&&(b=b.toLowerCase());return b},La=function(a,b){b&&!a.l&&(X(a),a.j=null,a.g.forEach(function(c,d){var e=d.toLowerCase();if(d!=e&&(Pa(this,d),Pa(this,e),0<c.length)){this.j=null;d=this.g;var g=d.set;e=Y(this,e);var h=c.length;if(0<h){const k=Array(h);for(let l=0;l<h;l++)k[l]=c[l];h=k}else h=[];g.call(d,e,h);this.h+=c.length}},a));a.l=b};const Sa={};function Ta(a,b){var c=Sa[a];if(void 0!==c&&(!c.D||Date.now()<=c.D+3E5))return c.p;c=new Promise((e,g)=>{b.onload=()=>e(b);b.onerror=h=>{b.parentNode&&b.parentNode.removeChild(b);g(h)};document.head.appendChild(b)});const d={D:0,p:c};c.catch(()=>d.D=+new Date);Sa[a]=d;return c}
var Ua=function(a){a=Na(a);const b=document.createElement("script");var c=a.toString();if(void 0===R){var d=null;var e=f.trustedTypes;if(e&&e.createPolicy){try{d=e.createPolicy("goog#html",{createHTML:n,createScript:n,createScriptURL:n})}catch(k){f.console&&f.console.error(k.message)}R=d}else R=d}c=(d=R)?d.createScriptURL(c):c;c=new S(c,Ba);b.src=c instanceof S&&c.constructor===S?c.g:"type_error:TrustedResourceUrl";var g;let h;(g=(c=null==(h=(g=(b.ownerDocument&&b.ownerDocument.defaultView||window).document).querySelector)?
void 0:h.call(g,"script[nonce]"))?c.nonce||c.getAttribute("nonce")||"":"")&&b.setAttribute("nonce",g);return Ta(a.toString(),b)};class Va{constructor(){this.promise=new Promise(a=>{this.g=a})}};var Z=function(a="Devsite has failed to load."){throw Error(a);},Xa=async function(){var a=Q;const b=new Va;m("__devsiteAppReadyResolver",b.g);m("__devsiteAppReadyPromise",b.promise);m("DevsiteApp.whenReady",()=>b.promise);if(O(a.g,12).length)try{await Promise.all(O(a.g,12).map(e=>{e=Na(e);const g=document.createElement("link");g.setAttribute("rel","stylesheet");g.setAttribute("type","text/css");g.setAttribute("href",e.toString());return Ta(e.toString(),g)}))}catch(e){Z(`Failed to load Devsite App dependencies: ${e.message}`)}const c=
f.DevsiteAppTenantCustomized?P(a.g,6):P(a.g,5);try{await Ua(`${c}${Wa(a)}`)}catch(e){if("en"!==a.g.getLocale()){oa(a.g);try{await Ua(`${c}${P(a.g,4)}`)}catch(g){Z(`Failed to load Devsite App binary: ${g.message}`)}}else Z(`Failed to load Devsite App binary: ${e.message}`)}const d=document;if("complete"!==d.readyState&&"interactive"!==d.readyState){const e=new Va;d.addEventListener("readystatechange",()=>{"interactive"!==d.readyState&&"complete"!==d.readyState||e.g()});await e.promise}},Wa=function(a){const b=
a.g.getLocale();a=P(a.g,4);return b&&"en"!==b?a.replace(/\.js$/,`__${b.toLowerCase().replace("-","_")}.js`):a};
const Q=new class{constructor(){this.h=null;this.g=new ya;this.j=[];this.l=a=>{this.j.push(a)};this.u=()=>{this.s()};if(f.__globalAppLoader)return f.__globalAppLoader;try{this.g=za()}catch(a){Z("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;m("__globalAppLoader",this);m("DevsiteApp.hasFlagAccess",a=>this.hasFlagAccess(a))}s(){var a=document.querySelector("devsite-content");a&&(window.removeEventListener("message",this.l),a.removeEventListener("devsite-content-updated",this.u));
a=window;for(const b of this.j)a.dispatchEvent(b);this.j=[]}getEnv(){if(na(this.g,11))return"PROD";const a=document.location.hostname;return a.endsWith("test.devsite.corp.google.com")||a.endsWith("test.devsite-v2-staging.googleplex.com")?"TEST":a.endsWith(".devsite.corp.google.com")||a.endsWith("devsite-v2-staging.googleplex.com")?"STAGE":"DEV"}hasFlagAccess(a){a:{var b=this.getEnv(),c=O(this.g,13),d=new URL(document.location.toString());d=new T(d.href);const e=Object.keys(q);if("PROD"!==b)for(const g of e)if(q[g]===
a&&(b=d.h.get(g),void 0!==b)){if("true"===b){a=!0;break a}if("false"===b){a=!1;break a}}a=Array.from(c).includes(a)}return a}},Ya=document.querySelector("devsite-content");Ya&&(window.addEventListener("message",Q.l),Ya.addEventListener("devsite-content-updated",Q.s.bind(Q)));
(async function(){const a=window;if("WeakMap"in a&&"performance"in a&&"now"in a.performance)return Q.h||(Q.h=Xa()),Q.h})().then(()=>{na(Q.g,9)?(f.DevsiteAppFrameboxInit||Z("Failed to load Devsite App binary"),DevsiteAppFrameboxInit(ta(),f.DevsiteAppAuthorizedElements)):(f.DevsiteAppInit||Z("Failed to load Devsite App binary"),DevsiteAppInit(ta(),f.DevsiteAppAuthorizedElements))});}).call(this);
