(function(_ds){var window=this;var YM=function(){return(0,_ds.P)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},ZM=function(){return(0,_ds.P)('<div class="devsite-book-nav-blur"></div>')},$M=function(a){a=a.Kp;a=_ds.KF(new _ds.GF("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.R(_ds.aq(1,_ds.yF[void 0]||1)),XXX_2:_ds.R(_ds.aq(a,_ds.yF[void 0]||1))});return(0,_ds.P)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var aN="onpointerover"in window?"pointerover":"mouseover",bN=function(a){const b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.D(a,"visually-hidden","",c))},jN=function(a){a.eventHandler.listen(a,"click",b=>void cN(a,b));a.eventHandler.listen(a,"keypress",b=>{13===b.keyCode&&cN(a,b)});a.eventHandler.listen(a,[aN,"focusin"],b=>void dN(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",
()=>{a.o&&(eN(a,"_book")?a.removeAttribute("top-level-nav"):_ds.D(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.K.g());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.K.g()});a.eventHandler.listen(a,"scroll",()=>{_ds.D(a,"user-scrolled","")});a.eventHandler.listen(a.g,"click",()=>{fN(a)});a.h&&(a.eventHandler.listen(a.h,"keyup",()=>void a.M.g()),a.eventHandler.listen(a.h,"focus",()=>void gN(a,"focus")));a.G&&a.eventHandler.listen(a.G,"click",
()=>{a.h&&(a.h.value="",a.h.focus());let b;null==(b=a.G)||b.classList.add("hidden");hN(a);iN(a);gN(a,"click")})},lN=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.D=new Set(b);if(!_ds.F().hash&&c)kN(a,a.D);else{c=new _ds.YF;for(const d of a.D)_ds.XF(c,d)}},mN=async function(a){const b=await _ds.x();for(const c of a.D)b.unregisterIntersectionForElement(c)},cN=function(a,b){if(!b.defaultPrevented){var c=b.target;"devsite-close-nav"===c.getAttribute("id")&&(b.preventDefault(),
b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.D(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&eN(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=b.target,g,h;if(!(null==(g=f)?0:null==(h=g.closest(".devsite-nav-title"))?
0:h.hasAttribute("href"))){for(b="click"===b.type||"touchend"===b.type;f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.D(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||(a.o&&(d=a.o.querySelector("[menu=_book]"))&&d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",
{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},dN=function(a,b){b.defaultPrevented||(b=_ds.ji(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.Qc(b,_ds.Pc(_ds.fj(b.href).href)))},fN=async function(a){var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;const c=b?document.documentElement.scrollTop/b:0;
_ds.Bk(a.eventHandler,a,_ds.lf,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.v.removeAttribute("animatable")});_ds.D(a,"animatable","");b=_ds.yc(a.j`animatable`);b(a.background,"animatable","");b(a.v,"animatable","");a.hasAttribute("collapsed")?(_ds.D(a,"aria-expanded","true",a.g),_ds.D(a,"aria-label","Hide side navigation",a.g),_ds.D(a,"data-title","Hide side navigation",a.g),a.removeAttribute("collapsed"),nN(a,"Expanded book nav")):(a.g.removeAttribute("aria-expanded"),
_ds.D(a,"aria-label","Show side navigation",a.g),_ds.D(a,"data-title","Show side navigation",a.g),_ds.D(a,"collapsed",""),nN(a,"Collapsed book nav"));await _ds.mj();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},gN=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:b,label:"focus"===b?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},
bubbles:!0}))},oN=function(a){a.J=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},qN=function(a){const b=_ds.F().searchParams.get("nf");a.h&&b&&(a.h.value=b,pN(a))},pN=function(a){if(a.J.length){hN(a);iN(a);var b,c,d=null==(b=a.h)?void 0:null==(c=b.value)?void 0:c.trim().toLowerCase();if(d){var e;null==(e=a.G)||e.classList.remove("hidden");for(const g of a.J){c=g.querySelectorAll(".devsite-nav-text");b=g.classList.contains("devsite-nav-expandable");
var f=e=!1;a=0;let h,k;if(d&&b&&(null==(h=g.querySelector(".devsite-nav-text"))?0:null==(k=h.textContent)?0:k.toLowerCase().includes(d)))f=e=!0;else for(const l of c){let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&(e=!0,++a)}if(!0===e){g.classList.remove("hidden");if(f){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const l of c){l.classList.remove("hidden");let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&++a}}c=void 0;(f=g.querySelector(".devsite-nav-text"))&&
(e=null==(c=f.textContent)?void 0:c.replace(new RegExp(`(${d})`,"ig"),"<mark>$1</mark>"))&&_ds.wc(f,_ds.Kg.g(e))}b&&0<a&&(b=g.querySelector(".devsite-nav-text"))&&(a=_ds.N($M,{Kp:a}),b.appendChild(a))}}else null==(f=a.G)||f.classList.add("hidden")}},hN=function(a){for(const b of a.J){let c;b.classList.toggle("hidden",!(null==(c=a.h)||!c.value))}},iN=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();
a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a){a=c.parentElement;let d;b=null==(d=a)?void 0:d.textContent;a&&b&&_ds.wc(a,_ds.Kg.g(b))}}},kN=async function(a,b){if(a.C){var c=await _ds.x(),d=new _ds.YF,e=f=>{f=f.target;_ds.XF(d,f);a.D.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},eN=function(a,b){let c=!1;if(a.o)for(const d of a.o.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),
c=!0):_ds.D(a,"hidden","",d);return c},rN=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active");a=_ds.sj(_ds.F().pathname);a=`[href="${_ds.fj(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active")},sN=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},uN=async function(a){a.C&&(a.removeAttribute("user-scrolled"),await _ds.mj(),await tN(a),await a.V,await _ds.x(),await _ds.mj(),await tN(a))},
tN=async function(a){if(a.C&&a.o){await _ds.x();var b=a.o.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await vN(a,b))}},vN=async function(a,b){if(a.C){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Rk(b,a,!0).y;await _ds.mj();c&&_ds.D(a,"user-scrolled","")}},nN=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))},wN=class extends _ds.E{constructor(){super();
this.C=!1;this.G=this.h=this.F=this.o=null;this.J=[];this.eventHandler=new _ds.H;this.T=()=>{};this.D=new Set;this.H=this.N=!1;this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.g=_ds.N(YM);this.v=_ds.N(ZM);this.V=new Promise(a=>{this.T=a});this.K=new _ds.xk(()=>{this.C&&bN(this)},20);this.M=new _ds.xk(()=>{pN(this)},20)}static get observedAttributes(){return["collapsed","fixed","hidden"]}async connectedCallback(){this.C=!0;_ds.Sg(this,this.j`animatable`,
this.j`aria-expanded`,this.j`aria-label`,this.j`collapsed`,this.j`data-title`,this.j`fixed`,this.j`has-book-nav`,this.j`hidden`,this.j`top-level-nav`,this.j`user-scrolled`,this.j`visually-hidden`);this.parentNode&&this.parentNode.insertBefore(this.background,this);this.hasAttribute("hidden")&&(_ds.D(this,"hidden","",this.g),_ds.D(this,"hidden","",this.v));const a=await _ds.x();if(this.N=a.hasFlagAccess(150)){let b;null==(b=this.parentElement)||b.insertBefore(this.g,this.nextSibling);_ds.D(this,"aria-label",
"Hide side navigation",this.g);_ds.D(this,"data-title","Hide side navigation",this.g);_ds.D(this,"aria-expanded","true",this.g);let c;null==(c=this.parentElement)||c.insertBefore(this.v,this.nextSibling)}if(this.H=a.hasFlagAccess(155))if(this.F=this.querySelector(".devsite-book-nav-filter"))this.h=this.F.querySelector("input[type=text]"),this.G=this.F.querySelector(".filter-clear-button"),oN(this),qN(this);bN(this);jN(this);await this.init();lN(this)}disconnectedCallback(){this.C=!1;_ds.I(this.eventHandler);
mN(this);this.D.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.D(this,"visually-hidden","",a);a=[this.background,this.g,this.v];for(const b of a)b&&_ds.Uh(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.v.removeAttribute("animatable");this.v.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",
{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.D(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);const c=[this.background,this.g,this.v];for(const d of c)d&&(b?_ds.D(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.T()}async init(a=!0){if(this.C){this.v.style.setProperty("--devsite-js-book-nav-scrollbar-width",
`${this.offsetWidth-this.clientWidth}px`);this.o=this.querySelector(".devsite-mobile-nav-bottom");_ds.D(this,"top-level-nav","");this.o&&this.o.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&_ds.D(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.D(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(rN(this),sN(this),await uN(this)):(await _ds.mj(),await tN(this))}}async qb(a){a?(a=a.querySelector("nav")||
null,rN(this,a),sN(this,a),a&&(await mN(this),this.D.clear(),lN(this,a,!1)),_ds.Vg(this,this.querySelector("nav"),a)):_ds.Sh(this);if(this.H&&(oN(this),this.h)){this.h.value="";let b;null==(b=this.G)||b.classList.add("hidden");qN(this)}await _ds.mj();await this.init(!1)}};wN.prototype.updateContent=wN.prototype.qb;wN.prototype.attributeChangedCallback=wN.prototype.attributeChangedCallback;wN.prototype.disconnectedCallback=wN.prototype.disconnectedCallback;wN.prototype.connectedCallback=wN.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",wN)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
