(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var bT=_ds.fh(function(){return!_ds.Sd||0<=_ds.Ia(_ds.II,9)}),cT=_ds.fh(function(){return _ds.Wd||_ds.Td||_ds.Vd&&0<=_ds.Ia(_ds.II,10)||_ds.Sd&&0<=_ds.Ia(_ds.II,10)}),eT=function(a,b){bT()&&(b=cT()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.Ik(a,dT(),b))},dT=_ds.fh(function(){return _ds.Sd&&9==_ds.oe?"-ms-transform":"transform"});var hT=function(a){a.h=fT(a,".devsite-top-logo-row-wrapper-wrapper");a.g=fT(a,".devsite-collapsible-section");a.o=fT(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.h}`);a.setAttribute("bottom-row--height",`${a.g}`);a.setAttribute("bottom-tabs--height",`${a.o}`);gT(a)},gT=function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.g&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.g-a.o&&a.hasAttribute("bottom-row--hidden")&&
a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.F&&(_ds.Ik(b,"transform",`translate3d(0, -${a.offset}px, 0)`),iT(a),a.F=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.v()}px`)},jT=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.I(a.G);a.C&&window.cancelAnimationFrame(a.C);c.removeAttribute("transition");a.removeAttribute("search-expanded");
var e=new _ds.sh(b.offsetWidth,b.offsetHeight);b=new _ds.sh(c.offsetWidth,c.offsetHeight);var f=_ds.al(c,"margin"),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.Ik(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});eT(c,a.hasAttribute("search-active")?0:e);_ds.Ck(a.G,d,_ds.lf,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");
n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),eT(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.C=window.requestAnimationFrame(()=>{c.setAttribute("transition","");if(bT()){var m=cT()?"scale3d("+l+",1,1)":"scale("+l+",1)";_ds.Ik(d,dT(),m)}eT(c,k)})}},kT=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");
var e=null==a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.nj(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled","")))}},mT=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.Y;_ds.li(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});
a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>lT(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{lT(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",
{bubbles:!0})))})},nT=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},iT=function(a){0===a.g?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},lT=function(a){window.requestAnimationFrame(()=>
a.J.g())},fT=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},oT=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},pT=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.Wg(a,c,b))},qT=class extends _ds.E{constructor(){super(...arguments);this.eventHandler=new _ds.H;this.F=
-1;this.G=new _ds.H;this.C=0;this.D=new MutationObserver(()=>hT(this));this.J=new _ds.yk(()=>{hT(this);iT(this)},15);this.authUser=void 0;this.offset=this.o=this.g=this.h=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;gT(this);break;case "search-active":jT(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),
c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),kT(this,a)}}connectedCallback(){mT(this);nT(this);iT(this);hT(this);this.D.observe(this,{childList:!0,subtree:!0});gT(this);const a=_ds.F();this.authUser=_ds.Pi(_ds.Qi(a.href),"authuser")}disconnectedCallback(){_ds.I(this.eventHandler);this.D.disconnect()}v(){return this.h+this.g-this.offset}H(){return this.h+this.g}kb(a){this.updated=!1;if(a){pT(this,a,".devsite-header-upper-tabs");
pT(this,a,".devsite-collapsible-section");pT(this,a,".devsite-product-name-wrapper");pT(this,a,"devsite-language-selector");pT(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&oT(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(oT(c,b),c=_ds.F(),c=_ds.Pi(_ds.Qi(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.Wg(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),
this.querySelector(".devsite-top-logo-row-middle"));_ds.Wg(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.Th(this),this.appendChild(a));nT(this);lT(this)}};try{window.customElements.define("devsite-header",qT)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
